#Region " DO NOT EDIT: This file is automatically generated "

'Only the associated template file should be edited directly.
'Helper class files are automatically regenerated from the template
'files at various times, including record actions and test object
'insertion actions.  Any changes made directly to a helper class
'file will be lost when automatically updated.

Imports Rational.Test.Ft.Object.Interfaces
Imports Rational.Test.Ft.Script
Imports Rational.Test.Ft.Vp



'Script Name   : HP97p29p33
'Generated     : 2007/06/24 3:30:29 PM
'Description   : Helper class for script
'Original Host : Windows XP x86 5.1 build 2600 Service Pack 2
 
'since  June 24, 2007
'author phl
 
Public MustInherit Class HP97p29p33Helper 
    Inherits RationalTestScript
    
    '
    ' Div: with default state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : ÷
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : π
    ' 		.classIndex : 0
    '
    Protected Function DivButton() As GuiTestObject
        DivButton = New GuiTestObject(GetMappedTestObject("DivButton"))
    End Function
    '
    ' Div: with specific test context and state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : ÷
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : π
    ' 		.classIndex : 0
    '
    Protected Function DivButton(anchor As TestObject, flags As Long) As  GuiTestObject
        DivButton = New GuiTestObject(GetMappedTestObject("DivButton"), anchor, flags)
    End Function
	
    '
    ' ENTER: with default state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : ENTER ↑
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : DEG
    ' 		.classIndex : 0
    '
    Protected Function ENTERButton() As GuiTestObject
        ENTERButton = New GuiTestObject(GetMappedTestObject("ENTERButton"))
    End Function
    '
    ' ENTER: with specific test context and state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : ENTER ↑
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : DEG
    ' 		.classIndex : 0
    '
    Protected Function ENTERButton(anchor As TestObject, flags As Long) As  GuiTestObject
        ENTERButton = New GuiTestObject(GetMappedTestObject("ENTERButton"), anchor, flags)
    End Function
	
    '
    ' HP97: with default state.
    '		Name : HP97
    ' 		TabIndex : 0
    ' 		Text : HP97
    ' 		.class : Mockingbird.HP.HP97.HP97
    ' 		.processName : Mockingbird.HP.HP97.exe
    '
    Protected Function HP97Window() As TopLevelSubitemTestObject
        HP97Window = New TopLevelSubitemTestObject(GetMappedTestObject("HP97Window"))
    End Function
    '
    ' HP97: with specific test context and state.
    '		Name : HP97
    ' 		TabIndex : 0
    ' 		Text : HP97
    ' 		.class : Mockingbird.HP.HP97.HP97
    ' 		.processName : Mockingbird.HP.HP97.exe
    '
    Protected Function HP97Window(anchor As TestObject, flags As Long) As  TopLevelSubitemTestObject
        HP97Window = New TopLevelSubitemTestObject(GetMappedTestObject("HP97Window"), anchor, flags)
    End Function
	
    '
    ' listBox: with default state.
    '		Name : listBox
    ' 		TabIndex : 0
    ' 		.class : System.Windows.Forms.ListBox
    ' 		.classIndex : 0
    '
    Protected Function ListBoxList() As SelectGuiSubitemTestObject
        ListBoxList = New SelectGuiSubitemTestObject(GetMappedTestObject("ListBoxList"))
    End Function
    '
    ' listBox: with specific test context and state.
    '		Name : listBox
    ' 		TabIndex : 0
    ' 		.class : System.Windows.Forms.ListBox
    ' 		.classIndex : 0
    '
    Protected Function ListBoxList(anchor As TestObject, flags As Long) As  SelectGuiSubitemTestObject
        ListBoxList = New SelectGuiSubitemTestObject(GetMappedTestObject("ListBoxList"), anchor, flags)
    End Function
	
    '
    ' menuStrip: with default state.
    '		Name : menuStrip
    ' 		TabIndex : 6
    ' 		.class : System.Windows.Forms.MenuStrip
    ' 		.classIndex : 0
    '
    Protected Function MenuStripMenuBar() As GuiSubitemTestObject
        MenuStripMenuBar = New GuiSubitemTestObject(GetMappedTestObject("MenuStripMenuBar"))
    End Function
    '
    ' menuStrip: with specific test context and state.
    '		Name : menuStrip
    ' 		TabIndex : 6
    ' 		.class : System.Windows.Forms.MenuStrip
    ' 		.classIndex : 0
    '
    Protected Function MenuStripMenuBar(anchor As TestObject, flags As Long) As  GuiSubitemTestObject
        MenuStripMenuBar = New GuiSubitemTestObject(GetMappedTestObject("MenuStripMenuBar"), anchor, flags)
    End Function
	
    '
    ' Mult: with default state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : ×
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : x≤y?
    ' 		.classIndex : 0
    '
    Protected Function MultButton() As GuiTestObject
        MultButton = New GuiTestObject(GetMappedTestObject("MultButton"))
    End Function
    '
    ' Mult: with specific test context and state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : ×
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : x≤y?
    ' 		.classIndex : 0
    '
    Protected Function MultButton(anchor As TestObject, flags As Long) As  GuiTestObject
        MultButton = New GuiTestObject(GetMappedTestObject("MultButton"), anchor, flags)
    End Function
	
    '
    ' numericTextBox: with default state.
    '		Name : numericTextBox
    ' 		TabIndex : 0
    ' 		.class : System.Windows.Forms.TextBox
    ' 		.classIndex : 0
    '
    Protected Function NumericTextBoxText() As TextGuiSubitemTestObject
        NumericTextBoxText = New TextGuiSubitemTestObject(GetMappedTestObject("NumericTextBoxText"))
    End Function
    '
    ' numericTextBox: with specific test context and state.
    '		Name : numericTextBox
    ' 		TabIndex : 0
    ' 		.class : System.Windows.Forms.TextBox
    ' 		.classIndex : 0
    '
    Protected Function NumericTextBoxText(anchor As TestObject, flags As Long) As  TextGuiSubitemTestObject
        NumericTextBoxText = New TextGuiSubitemTestObject(GetMappedTestObject("NumericTextBoxText"), anchor, flags)
    End Function
	
    '
    ' PRINTX: with default state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : PRINT x
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : STACK
    ' 		.classIndex : 0
    '
    Protected Function PRINTXButton() As GuiTestObject
        PRINTXButton = New GuiTestObject(GetMappedTestObject("PRINTXButton"))
    End Function
    '
    ' PRINTX: with specific test context and state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : PRINT x
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : STACK
    ' 		.classIndex : 0
    '
    Protected Function PRINTXButton(anchor As TestObject, flags As Long) As  GuiTestObject
        PRINTXButton = New GuiTestObject(GetMappedTestObject("PRINTXButton"), anchor, flags)
    End Function
	
    '
    ' Period: with default state.
    '		Name : button
    ' 		Text :  ・
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : MERGE
    ' 		.classIndex : 0
    '
    Protected Function PeriodButton() As GuiTestObject
        PeriodButton = New GuiTestObject(GetMappedTestObject("PeriodButton"))
    End Function
    '
    ' Period: with specific test context and state.
    '		Name : button
    ' 		Text :  ・
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : MERGE
    ' 		.classIndex : 0
    '
    Protected Function PeriodButton(anchor As TestObject, flags As Long) As  GuiTestObject
        PeriodButton = New GuiTestObject(GetMappedTestObject("PeriodButton"), anchor, flags)
    End Function
	
    '
    ' Plus: with default state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : +
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : H.MS+
    ' 		.classIndex : 0
    '
    Protected Function PlusButton() As GuiTestObject
        PlusButton = New GuiTestObject(GetMappedTestObject("PlusButton"))
    End Function
    '
    ' Plus: with specific test context and state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : +
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : H.MS+
    ' 		.classIndex : 0
    '
    Protected Function PlusButton(anchor As TestObject, flags As Long) As  GuiTestObject
        PlusButton = New GuiTestObject(GetMappedTestObject("PlusButton"), anchor, flags)
    End Function
	
    '
    ' Sqrt: with default state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : √x̅
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : S
    ' 		.classIndex : 0
    '
    Protected Function SqrtButton() As GuiTestObject
        SqrtButton = New GuiTestObject(GetMappedTestObject("SqrtButton"))
    End Function
    '
    ' Sqrt: with specific test context and state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : √x̅
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : S
    ' 		.classIndex : 0
    '
    Protected Function SqrtButton(anchor As TestObject, flags As Long) As  GuiTestObject
        SqrtButton = New GuiTestObject(GetMappedTestObject("SqrtButton"), anchor, flags)
    End Function
	
    '
    ' Sub: with default state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : -
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : x<0?
    ' 		.classIndex : 0
    '
    Protected Function SubButton() As GuiTestObject
        SubButton = New GuiTestObject(GetMappedTestObject("SubButton"))
    End Function
    '
    ' Sub: with specific test context and state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : -
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : x<0?
    ' 		.classIndex : 0
    '
    Protected Function SubButton(anchor As TestObject, flags As Long) As  GuiTestObject
        SubButton = New GuiTestObject(GetMappedTestObject("SubButton"), anchor, flags)
    End Function
	
    '
    ' toggleManTraceNorm: with default state.
    '		Name : button
    ' 		TabIndex : 5
    ' 		Text : 
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : TRACE
    ' 		.classIndex : 0
    '
    Protected Function ToggleManTraceNormButton() As GuiTestObject
        ToggleManTraceNormButton = New GuiTestObject(GetMappedTestObject("ToggleManTraceNormButton"))
    End Function
    '
    ' toggleManTraceNorm: with specific test context and state.
    '		Name : button
    ' 		TabIndex : 5
    ' 		Text : 
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : TRACE
    ' 		.classIndex : 0
    '
    Protected Function ToggleManTraceNormButton(anchor As TestObject, flags As Long) As  GuiTestObject
        ToggleManTraceNormButton = New GuiTestObject(GetMappedTestObject("ToggleManTraceNormButton"), anchor, flags)
    End Function
	
    '
    ' _0: with default state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : 0
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : WRITE DATA
    ' 		.classIndex : 0
    '
    Protected Function _0Button() As GuiTestObject
        _0Button = New GuiTestObject(GetMappedTestObject("_0Button"))
    End Function
    '
    ' _0: with specific test context and state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : 0
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : WRITE DATA
    ' 		.classIndex : 0
    '
    Protected Function _0Button(anchor As TestObject, flags As Long) As  GuiTestObject
        _0Button = New GuiTestObject(GetMappedTestObject("_0Button"), anchor, flags)
    End Function
	
    '
    ' _1: with default state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : DEL
    ' 		.classIndex : 0
    '
    Protected Function _1Button() As GuiTestObject
        _1Button = New GuiTestObject(GetMappedTestObject("_1Button"))
    End Function
    '
    ' _1: with specific test context and state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : DEL
    ' 		.classIndex : 0
    '
    Protected Function _1Button(anchor As TestObject, flags As Long) As  GuiTestObject
        _1Button = New GuiTestObject(GetMappedTestObject("_1Button"), anchor, flags)
    End Function
	
    '
    ' _2: with default state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : 2
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : CL REG
    ' 		.classIndex : 0
    '
    Protected Function _2Button() As GuiTestObject
        _2Button = New GuiTestObject(GetMappedTestObject("_2Button"))
    End Function
    '
    ' _2: with specific test context and state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : 2
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : CL REG
    ' 		.classIndex : 0
    '
    Protected Function _2Button(anchor As TestObject, flags As Long) As  GuiTestObject
        _2Button = New GuiTestObject(GetMappedTestObject("_2Button"), anchor, flags)
    End Function
	
    '
    ' _3: with default state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : 3
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : CL PGRM
    ' 		.classIndex : 0
    '
    Protected Function _3Button() As GuiTestObject
        _3Button = New GuiTestObject(GetMappedTestObject("_3Button"))
    End Function
    '
    ' _3: with specific test context and state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : 3
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : CL PGRM
    ' 		.classIndex : 0
    '
    Protected Function _3Button(anchor As TestObject, flags As Long) As  GuiTestObject
        _3Button = New GuiTestObject(GetMappedTestObject("_3Button"), anchor, flags)
    End Function
	
    '
    ' _4: with default state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : 4
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : x≠0?
    ' 		.classIndex : 0
    '
    Protected Function _4Button() As GuiTestObject
        _4Button = New GuiTestObject(GetMappedTestObject("_4Button"))
    End Function
    '
    ' _4: with specific test context and state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : 4
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : x≠0?
    ' 		.classIndex : 0
    '
    Protected Function _4Button(anchor As TestObject, flags As Long) As  GuiTestObject
        _4Button = New GuiTestObject(GetMappedTestObject("_4Button"), anchor, flags)
    End Function
	
    '
    ' _5: with default state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : 5
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : x=0?
    ' 		.classIndex : 0
    '
    Protected Function _5Button() As GuiTestObject
        _5Button = New GuiTestObject(GetMappedTestObject("_5Button"))
    End Function
    '
    ' _5: with specific test context and state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : 5
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : x=0?
    ' 		.classIndex : 0
    '
    Protected Function _5Button(anchor As TestObject, flags As Long) As  GuiTestObject
        _5Button = New GuiTestObject(GetMappedTestObject("_5Button"), anchor, flags)
    End Function
	
    '
    ' _6: with default state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : 6
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : x>0?
    ' 		.classIndex : 0
    '
    Protected Function _6Button() As GuiTestObject
        _6Button = New GuiTestObject(GetMappedTestObject("_6Button"))
    End Function
    '
    ' _6: with specific test context and state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : 6
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : x>0?
    ' 		.classIndex : 0
    '
    Protected Function _6Button(anchor As TestObject, flags As Long) As  GuiTestObject
        _6Button = New GuiTestObject(GetMappedTestObject("_6Button"), anchor, flags)
    End Function
	
    '
    ' _7: with default state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : 7
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : x≠y?
    ' 		.classIndex : 0
    '
    Protected Function _7Button() As GuiTestObject
        _7Button = New GuiTestObject(GetMappedTestObject("_7Button"))
    End Function
    '
    ' _7: with specific test context and state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : 7
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : x≠y?
    ' 		.classIndex : 0
    '
    Protected Function _7Button(anchor As TestObject, flags As Long) As  GuiTestObject
        _7Button = New GuiTestObject(GetMappedTestObject("_7Button"), anchor, flags)
    End Function
	
    '
    ' _8: with default state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : 8
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : x=y?
    ' 		.classIndex : 0
    '
    Protected Function _8Button() As GuiTestObject
        _8Button = New GuiTestObject(GetMappedTestObject("_8Button"))
    End Function
    '
    ' _8: with specific test context and state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : 8
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : x=y?
    ' 		.classIndex : 0
    '
    Protected Function _8Button(anchor As TestObject, flags As Long) As  GuiTestObject
        _8Button = New GuiTestObject(GetMappedTestObject("_8Button"), anchor, flags)
    End Function
	
    '
    ' _9: with default state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : 9
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : x>y?
    ' 		.classIndex : 0
    '
    Protected Function _9Button() As GuiTestObject
        _9Button = New GuiTestObject(GetMappedTestObject("_9Button"))
    End Function
    '
    ' _9: with specific test context and state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : 9
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : x>y?
    ' 		.classIndex : 0
    '
    Protected Function _9Button(anchor As TestObject, flags As Long) As  GuiTestObject
        _9Button = New GuiTestObject(GetMappedTestObject("_9Button"), anchor, flags)
    End Function
	
    '
    ' Locate and return the verification point listBox_list_1 object in the SUT.
    '
    Protected Function listBox_list_1VP() As IFtVerificationPoint
        listBox_list_1VP = vp("listBox_list_1")
    End Function
    Protected Function listBox_list_1VP(anchor As TestObject)As IFtVerificationPoint
        listBox_list_1VP = vp("listBox_list_1", anchor)
    End Function
	
    '
    ' Locate and return the verification point listBox_list_10 object in the SUT.
    '
    Protected Function listBox_list_10VP() As IFtVerificationPoint
        listBox_list_10VP = vp("listBox_list_10")
    End Function
    Protected Function listBox_list_10VP(anchor As TestObject)As IFtVerificationPoint
        listBox_list_10VP = vp("listBox_list_10", anchor)
    End Function
	
    '
    ' Locate and return the verification point listBox_list_2 object in the SUT.
    '
    Protected Function listBox_list_2VP() As IFtVerificationPoint
        listBox_list_2VP = vp("listBox_list_2")
    End Function
    Protected Function listBox_list_2VP(anchor As TestObject)As IFtVerificationPoint
        listBox_list_2VP = vp("listBox_list_2", anchor)
    End Function
	
    '
    ' Locate and return the verification point listBox_list_3 object in the SUT.
    '
    Protected Function listBox_list_3VP() As IFtVerificationPoint
        listBox_list_3VP = vp("listBox_list_3")
    End Function
    Protected Function listBox_list_3VP(anchor As TestObject)As IFtVerificationPoint
        listBox_list_3VP = vp("listBox_list_3", anchor)
    End Function
	
    '
    ' Locate and return the verification point listBox_list_4 object in the SUT.
    '
    Protected Function listBox_list_4VP() As IFtVerificationPoint
        listBox_list_4VP = vp("listBox_list_4")
    End Function
    Protected Function listBox_list_4VP(anchor As TestObject)As IFtVerificationPoint
        listBox_list_4VP = vp("listBox_list_4", anchor)
    End Function
	
    '
    ' Locate and return the verification point listBox_list_5 object in the SUT.
    '
    Protected Function listBox_list_5VP() As IFtVerificationPoint
        listBox_list_5VP = vp("listBox_list_5")
    End Function
    Protected Function listBox_list_5VP(anchor As TestObject)As IFtVerificationPoint
        listBox_list_5VP = vp("listBox_list_5", anchor)
    End Function
	
    '
    ' Locate and return the verification point listBox_list_6 object in the SUT.
    '
    Protected Function listBox_list_6VP() As IFtVerificationPoint
        listBox_list_6VP = vp("listBox_list_6")
    End Function
    Protected Function listBox_list_6VP(anchor As TestObject)As IFtVerificationPoint
        listBox_list_6VP = vp("listBox_list_6", anchor)
    End Function
	
    '
    ' Locate and return the verification point listBox_list_7 object in the SUT.
    '
    Protected Function listBox_list_7VP() As IFtVerificationPoint
        listBox_list_7VP = vp("listBox_list_7")
    End Function
    Protected Function listBox_list_7VP(anchor As TestObject)As IFtVerificationPoint
        listBox_list_7VP = vp("listBox_list_7", anchor)
    End Function
	
    '
    ' Locate and return the verification point listBox_list_8 object in the SUT.
    '
    Protected Function listBox_list_8VP() As IFtVerificationPoint
        listBox_list_8VP = vp("listBox_list_8")
    End Function
    Protected Function listBox_list_8VP(anchor As TestObject)As IFtVerificationPoint
        listBox_list_8VP = vp("listBox_list_8", anchor)
    End Function
	
    '
    ' Locate and return the verification point listBox_list_9 object in the SUT.
    '
    Protected Function listBox_list_9VP() As IFtVerificationPoint
        listBox_list_9VP = vp("listBox_list_9")
    End Function
    Protected Function listBox_list_9VP(anchor As TestObject)As IFtVerificationPoint
        listBox_list_9VP = vp("listBox_list_9", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_1 object in the SUT.
    '
    Protected Function numericTextBox_standard_1VP() As IFtVerificationPoint
        numericTextBox_standard_1VP = vp("numericTextBox_standard_1")
    End Function
    Protected Function numericTextBox_standard_1VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_1VP = vp("numericTextBox_standard_1", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_10 object in the SUT.
    '
    Protected Function numericTextBox_standard_10VP() As IFtVerificationPoint
        numericTextBox_standard_10VP = vp("numericTextBox_standard_10")
    End Function
    Protected Function numericTextBox_standard_10VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_10VP = vp("numericTextBox_standard_10", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_11 object in the SUT.
    '
    Protected Function numericTextBox_standard_11VP() As IFtVerificationPoint
        numericTextBox_standard_11VP = vp("numericTextBox_standard_11")
    End Function
    Protected Function numericTextBox_standard_11VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_11VP = vp("numericTextBox_standard_11", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_12 object in the SUT.
    '
    Protected Function numericTextBox_standard_12VP() As IFtVerificationPoint
        numericTextBox_standard_12VP = vp("numericTextBox_standard_12")
    End Function
    Protected Function numericTextBox_standard_12VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_12VP = vp("numericTextBox_standard_12", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_13 object in the SUT.
    '
    Protected Function numericTextBox_standard_13VP() As IFtVerificationPoint
        numericTextBox_standard_13VP = vp("numericTextBox_standard_13")
    End Function
    Protected Function numericTextBox_standard_13VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_13VP = vp("numericTextBox_standard_13", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_14 object in the SUT.
    '
    Protected Function numericTextBox_standard_14VP() As IFtVerificationPoint
        numericTextBox_standard_14VP = vp("numericTextBox_standard_14")
    End Function
    Protected Function numericTextBox_standard_14VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_14VP = vp("numericTextBox_standard_14", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_15 object in the SUT.
    '
    Protected Function numericTextBox_standard_15VP() As IFtVerificationPoint
        numericTextBox_standard_15VP = vp("numericTextBox_standard_15")
    End Function
    Protected Function numericTextBox_standard_15VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_15VP = vp("numericTextBox_standard_15", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_16 object in the SUT.
    '
    Protected Function numericTextBox_standard_16VP() As IFtVerificationPoint
        numericTextBox_standard_16VP = vp("numericTextBox_standard_16")
    End Function
    Protected Function numericTextBox_standard_16VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_16VP = vp("numericTextBox_standard_16", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_17 object in the SUT.
    '
    Protected Function numericTextBox_standard_17VP() As IFtVerificationPoint
        numericTextBox_standard_17VP = vp("numericTextBox_standard_17")
    End Function
    Protected Function numericTextBox_standard_17VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_17VP = vp("numericTextBox_standard_17", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_18 object in the SUT.
    '
    Protected Function numericTextBox_standard_18VP() As IFtVerificationPoint
        numericTextBox_standard_18VP = vp("numericTextBox_standard_18")
    End Function
    Protected Function numericTextBox_standard_18VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_18VP = vp("numericTextBox_standard_18", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_19 object in the SUT.
    '
    Protected Function numericTextBox_standard_19VP() As IFtVerificationPoint
        numericTextBox_standard_19VP = vp("numericTextBox_standard_19")
    End Function
    Protected Function numericTextBox_standard_19VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_19VP = vp("numericTextBox_standard_19", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_2 object in the SUT.
    '
    Protected Function numericTextBox_standard_2VP() As IFtVerificationPoint
        numericTextBox_standard_2VP = vp("numericTextBox_standard_2")
    End Function
    Protected Function numericTextBox_standard_2VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_2VP = vp("numericTextBox_standard_2", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_20 object in the SUT.
    '
    Protected Function numericTextBox_standard_20VP() As IFtVerificationPoint
        numericTextBox_standard_20VP = vp("numericTextBox_standard_20")
    End Function
    Protected Function numericTextBox_standard_20VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_20VP = vp("numericTextBox_standard_20", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_21 object in the SUT.
    '
    Protected Function numericTextBox_standard_21VP() As IFtVerificationPoint
        numericTextBox_standard_21VP = vp("numericTextBox_standard_21")
    End Function
    Protected Function numericTextBox_standard_21VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_21VP = vp("numericTextBox_standard_21", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_22 object in the SUT.
    '
    Protected Function numericTextBox_standard_22VP() As IFtVerificationPoint
        numericTextBox_standard_22VP = vp("numericTextBox_standard_22")
    End Function
    Protected Function numericTextBox_standard_22VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_22VP = vp("numericTextBox_standard_22", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_23 object in the SUT.
    '
    Protected Function numericTextBox_standard_23VP() As IFtVerificationPoint
        numericTextBox_standard_23VP = vp("numericTextBox_standard_23")
    End Function
    Protected Function numericTextBox_standard_23VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_23VP = vp("numericTextBox_standard_23", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_24 object in the SUT.
    '
    Protected Function numericTextBox_standard_24VP() As IFtVerificationPoint
        numericTextBox_standard_24VP = vp("numericTextBox_standard_24")
    End Function
    Protected Function numericTextBox_standard_24VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_24VP = vp("numericTextBox_standard_24", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_25 object in the SUT.
    '
    Protected Function numericTextBox_standard_25VP() As IFtVerificationPoint
        numericTextBox_standard_25VP = vp("numericTextBox_standard_25")
    End Function
    Protected Function numericTextBox_standard_25VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_25VP = vp("numericTextBox_standard_25", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_26 object in the SUT.
    '
    Protected Function numericTextBox_standard_26VP() As IFtVerificationPoint
        numericTextBox_standard_26VP = vp("numericTextBox_standard_26")
    End Function
    Protected Function numericTextBox_standard_26VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_26VP = vp("numericTextBox_standard_26", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_27 object in the SUT.
    '
    Protected Function numericTextBox_standard_27VP() As IFtVerificationPoint
        numericTextBox_standard_27VP = vp("numericTextBox_standard_27")
    End Function
    Protected Function numericTextBox_standard_27VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_27VP = vp("numericTextBox_standard_27", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_28 object in the SUT.
    '
    Protected Function numericTextBox_standard_28VP() As IFtVerificationPoint
        numericTextBox_standard_28VP = vp("numericTextBox_standard_28")
    End Function
    Protected Function numericTextBox_standard_28VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_28VP = vp("numericTextBox_standard_28", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_29 object in the SUT.
    '
    Protected Function numericTextBox_standard_29VP() As IFtVerificationPoint
        numericTextBox_standard_29VP = vp("numericTextBox_standard_29")
    End Function
    Protected Function numericTextBox_standard_29VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_29VP = vp("numericTextBox_standard_29", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_3 object in the SUT.
    '
    Protected Function numericTextBox_standard_3VP() As IFtVerificationPoint
        numericTextBox_standard_3VP = vp("numericTextBox_standard_3")
    End Function
    Protected Function numericTextBox_standard_3VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_3VP = vp("numericTextBox_standard_3", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_30 object in the SUT.
    '
    Protected Function numericTextBox_standard_30VP() As IFtVerificationPoint
        numericTextBox_standard_30VP = vp("numericTextBox_standard_30")
    End Function
    Protected Function numericTextBox_standard_30VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_30VP = vp("numericTextBox_standard_30", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_31 object in the SUT.
    '
    Protected Function numericTextBox_standard_31VP() As IFtVerificationPoint
        numericTextBox_standard_31VP = vp("numericTextBox_standard_31")
    End Function
    Protected Function numericTextBox_standard_31VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_31VP = vp("numericTextBox_standard_31", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_32 object in the SUT.
    '
    Protected Function numericTextBox_standard_32VP() As IFtVerificationPoint
        numericTextBox_standard_32VP = vp("numericTextBox_standard_32")
    End Function
    Protected Function numericTextBox_standard_32VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_32VP = vp("numericTextBox_standard_32", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_33 object in the SUT.
    '
    Protected Function numericTextBox_standard_33VP() As IFtVerificationPoint
        numericTextBox_standard_33VP = vp("numericTextBox_standard_33")
    End Function
    Protected Function numericTextBox_standard_33VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_33VP = vp("numericTextBox_standard_33", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_34 object in the SUT.
    '
    Protected Function numericTextBox_standard_34VP() As IFtVerificationPoint
        numericTextBox_standard_34VP = vp("numericTextBox_standard_34")
    End Function
    Protected Function numericTextBox_standard_34VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_34VP = vp("numericTextBox_standard_34", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_35 object in the SUT.
    '
    Protected Function numericTextBox_standard_35VP() As IFtVerificationPoint
        numericTextBox_standard_35VP = vp("numericTextBox_standard_35")
    End Function
    Protected Function numericTextBox_standard_35VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_35VP = vp("numericTextBox_standard_35", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_36 object in the SUT.
    '
    Protected Function numericTextBox_standard_36VP() As IFtVerificationPoint
        numericTextBox_standard_36VP = vp("numericTextBox_standard_36")
    End Function
    Protected Function numericTextBox_standard_36VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_36VP = vp("numericTextBox_standard_36", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_37 object in the SUT.
    '
    Protected Function numericTextBox_standard_37VP() As IFtVerificationPoint
        numericTextBox_standard_37VP = vp("numericTextBox_standard_37")
    End Function
    Protected Function numericTextBox_standard_37VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_37VP = vp("numericTextBox_standard_37", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_4 object in the SUT.
    '
    Protected Function numericTextBox_standard_4VP() As IFtVerificationPoint
        numericTextBox_standard_4VP = vp("numericTextBox_standard_4")
    End Function
    Protected Function numericTextBox_standard_4VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_4VP = vp("numericTextBox_standard_4", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_5 object in the SUT.
    '
    Protected Function numericTextBox_standard_5VP() As IFtVerificationPoint
        numericTextBox_standard_5VP = vp("numericTextBox_standard_5")
    End Function
    Protected Function numericTextBox_standard_5VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_5VP = vp("numericTextBox_standard_5", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_6 object in the SUT.
    '
    Protected Function numericTextBox_standard_6VP() As IFtVerificationPoint
        numericTextBox_standard_6VP = vp("numericTextBox_standard_6")
    End Function
    Protected Function numericTextBox_standard_6VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_6VP = vp("numericTextBox_standard_6", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_7 object in the SUT.
    '
    Protected Function numericTextBox_standard_7VP() As IFtVerificationPoint
        numericTextBox_standard_7VP = vp("numericTextBox_standard_7")
    End Function
    Protected Function numericTextBox_standard_7VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_7VP = vp("numericTextBox_standard_7", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_8 object in the SUT.
    '
    Protected Function numericTextBox_standard_8VP() As IFtVerificationPoint
        numericTextBox_standard_8VP = vp("numericTextBox_standard_8")
    End Function
    Protected Function numericTextBox_standard_8VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_8VP = vp("numericTextBox_standard_8", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_9 object in the SUT.
    '
    Protected Function numericTextBox_standard_9VP() As IFtVerificationPoint
        numericTextBox_standard_9VP = vp("numericTextBox_standard_9")
    End Function
    Protected Function numericTextBox_standard_9VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_9VP = vp("numericTextBox_standard_9", anchor)
    End Function
	
    

    Protected Sub New()
        Dim ISI As Rational.Test.Ft.Script.Impl.IScriptInternal = Me
        ISI.SetScriptName("HP97p29p33")
    End Sub
End Class
	

#End Region

