#Region " DO NOT EDIT: This file is automatically generated "

'Only the associated template file should be edited directly.
'Helper class files are automatically regenerated from the template
'files at various times, including record actions and test object
'insertion actions.  Any changes made directly to a helper class
'file will be lost when automatically updated.

Imports Rational.Test.Ft.Object.Interfaces
Imports Rational.Test.Ft.Script
Imports Rational.Test.Ft.Vp



'Script Name   : HP97p35p39
'Generated     : 2007/06/24 4:32:31 PM
'Description   : Helper class for script
'Original Host : Windows XP x86 5.1 build 2600 Service Pack 2
 
'since  June 24, 2007
'author phl
 
Public MustInherit Class HP97p35p39Helper 
    Inherits RationalTestScript
    
    '
    ' DSP: with default state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : DSP
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : LAST x
    ' 		.classIndex : 0
    '
    Protected Function DSPButton() As GuiTestObject
        DSPButton = New GuiTestObject(GetMappedTestObject("DSPButton"))
    End Function
    '
    ' DSP: with specific test context and state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : DSP
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : LAST x
    ' 		.classIndex : 0
    '
    Protected Function DSPButton(anchor As TestObject, flags As Long) As  GuiTestObject
        DSPButton = New GuiTestObject(GetMappedTestObject("DSPButton"), anchor, flags)
    End Function
	
    '
    ' ENG: with default state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : ENG
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : REG
    ' 		.classIndex : 0
    '
    Protected Function ENGButton() As GuiTestObject
        ENGButton = New GuiTestObject(GetMappedTestObject("ENGButton"))
    End Function
    '
    ' ENG: with specific test context and state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : ENG
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : REG
    ' 		.classIndex : 0
    '
    Protected Function ENGButton(anchor As TestObject, flags As Long) As  GuiTestObject
        ENGButton = New GuiTestObject(GetMappedTestObject("ENGButton"), anchor, flags)
    End Function
	
    '
    ' ENTER: with default state.
    '		Name : button
    ' 		Text : ENTER ↑
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : DEG
    ' 		.classIndex : 0
    '
    Protected Function ENTERButton() As GuiTestObject
        ENTERButton = New GuiTestObject(GetMappedTestObject("ENTERButton"))
    End Function
    '
    ' ENTER: with specific test context and state.
    '		Name : button
    ' 		Text : ENTER ↑
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : DEG
    ' 		.classIndex : 0
    '
    Protected Function ENTERButton(anchor As TestObject, flags As Long) As  GuiTestObject
        ENTERButton = New GuiTestObject(GetMappedTestObject("ENTERButton"), anchor, flags)
    End Function
	
    '
    ' FIX: with default state.
    '		Name : button
    ' 		Text : FIX
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : SPACE
    ' 		.classIndex : 0
    '
    Protected Function FIXButton() As GuiTestObject
        FIXButton = New GuiTestObject(GetMappedTestObject("FIXButton"))
    End Function
    '
    ' FIX: with specific test context and state.
    '		Name : button
    ' 		Text : FIX
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : SPACE
    ' 		.classIndex : 0
    '
    Protected Function FIXButton(anchor As TestObject, flags As Long) As  GuiTestObject
        FIXButton = New GuiTestObject(GetMappedTestObject("FIXButton"), anchor, flags)
    End Function
	
    '
    ' HP97: with default state.
    '		Name : HP97
    ' 		Text : HP97
    ' 		TabIndex : 0
    ' 		.class : Mockingbird.HP.HP97.HP97
    ' 		.processName : Mockingbird.HP.HP97.exe
    '
    Protected Function HP97Window() As TopLevelSubitemTestObject
        HP97Window = New TopLevelSubitemTestObject(GetMappedTestObject("HP97Window"))
    End Function
    '
    ' HP97: with specific test context and state.
    '		Name : HP97
    ' 		Text : HP97
    ' 		TabIndex : 0
    ' 		.class : Mockingbird.HP.HP97.HP97
    ' 		.processName : Mockingbird.HP.HP97.exe
    '
    Protected Function HP97Window(anchor As TestObject, flags As Long) As  TopLevelSubitemTestObject
        HP97Window = New TopLevelSubitemTestObject(GetMappedTestObject("HP97Window"), anchor, flags)
    End Function
	
    '
    ' Mult: with default state.
    '		Name : button
    ' 		Text : ×
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : x≤y?
    ' 		.classIndex : 0
    '
    Protected Function MultButton() As GuiTestObject
        MultButton = New GuiTestObject(GetMappedTestObject("MultButton"))
    End Function
    '
    ' Mult: with specific test context and state.
    '		Name : button
    ' 		Text : ×
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : x≤y?
    ' 		.classIndex : 0
    '
    Protected Function MultButton(anchor As TestObject, flags As Long) As  GuiTestObject
        MultButton = New GuiTestObject(GetMappedTestObject("MultButton"), anchor, flags)
    End Function
	
    '
    ' numericTextBox: with default state.
    '		Name : numericTextBox
    ' 		TabIndex : 0
    ' 		.class : System.Windows.Forms.TextBox
    ' 		.classIndex : 0
    '
    Protected Function NumericTextBoxText() As TextGuiSubitemTestObject
        NumericTextBoxText = New TextGuiSubitemTestObject(GetMappedTestObject("NumericTextBoxText"))
    End Function
    '
    ' numericTextBox: with specific test context and state.
    '		Name : numericTextBox
    ' 		TabIndex : 0
    ' 		.class : System.Windows.Forms.TextBox
    ' 		.classIndex : 0
    '
    Protected Function NumericTextBoxText(anchor As TestObject, flags As Long) As  TextGuiSubitemTestObject
        NumericTextBoxText = New TextGuiSubitemTestObject(GetMappedTestObject("NumericTextBoxText"), anchor, flags)
    End Function
	
    '
    ' Period: with default state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text :  ・
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : MERGE
    ' 		.classIndex : 0
    '
    Protected Function PeriodButton() As GuiTestObject
        PeriodButton = New GuiTestObject(GetMappedTestObject("PeriodButton"))
    End Function
    '
    ' Period: with specific test context and state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text :  ・
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : MERGE
    ' 		.classIndex : 0
    '
    Protected Function PeriodButton(anchor As TestObject, flags As Long) As  GuiTestObject
        PeriodButton = New GuiTestObject(GetMappedTestObject("PeriodButton"), anchor, flags)
    End Function
	
    '
    ' R: with default state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : R↓
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : R↑
    ' 		.classIndex : 0
    '
    Protected Function RButton() As GuiTestObject
        RButton = New GuiTestObject(GetMappedTestObject("RButton"))
    End Function
    '
    ' R: with specific test context and state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : R↓
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : R↑
    ' 		.classIndex : 0
    '
    Protected Function RButton(anchor As TestObject, flags As Long) As  GuiTestObject
        RButton = New GuiTestObject(GetMappedTestObject("RButton"), anchor, flags)
    End Function
	
    '
    ' SCI: with default state.
    '		Name : button
    ' 		Text : SCI
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : PRGM
    ' 		.classIndex : 0
    '
    Protected Function SCIButton() As GuiTestObject
        SCIButton = New GuiTestObject(GetMappedTestObject("SCIButton"))
    End Function
    '
    ' SCI: with specific test context and state.
    '		Name : button
    ' 		Text : SCI
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : PRGM
    ' 		.classIndex : 0
    '
    Protected Function SCIButton(anchor As TestObject, flags As Long) As  GuiTestObject
        SCIButton = New GuiTestObject(GetMappedTestObject("SCIButton"), anchor, flags)
    End Function
	
    '
    ' toggleManTraceNorm: with default state.
    '		Name : button
    ' 		Text : 
    ' 		TabIndex : 5
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : TRACE
    ' 		.classIndex : 0
    '
    Protected Function ToggleManTraceNormButton() As GuiTestObject
        ToggleManTraceNormButton = New GuiTestObject(GetMappedTestObject("ToggleManTraceNormButton"))
    End Function
    '
    ' toggleManTraceNorm: with specific test context and state.
    '		Name : button
    ' 		Text : 
    ' 		TabIndex : 5
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : TRACE
    ' 		.classIndex : 0
    '
    Protected Function ToggleManTraceNormButton(anchor As TestObject, flags As Long) As  GuiTestObject
        ToggleManTraceNormButton = New GuiTestObject(GetMappedTestObject("ToggleManTraceNormButton"), anchor, flags)
    End Function
	
    '
    ' ToggleOffOnButton: with default state.
    '		Name : button
    ' 		TabIndex : 5
    ' 		Text : 
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function ToggleOffOnButton() As GuiTestObject
        ToggleOffOnButton = New GuiTestObject(GetMappedTestObject("ToggleOffOnButton"))
    End Function
    '
    ' ToggleOffOnButton: with specific test context and state.
    '		Name : button
    ' 		TabIndex : 5
    ' 		Text : 
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function ToggleOffOnButton(anchor As TestObject, flags As Long) As  GuiTestObject
        ToggleOffOnButton = New GuiTestObject(GetMappedTestObject("ToggleOffOnButton"), anchor, flags)
    End Function
	
    '
    ' toggleWprgmRunButton: with default state.
    '		Name : button
    ' 		Text : 
    ' 		TabIndex : 5
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function ToggleWprgmRunButtonButton() As GuiTestObject
        ToggleWprgmRunButtonButton = New GuiTestObject(GetMappedTestObject("ToggleWprgmRunButtonButton"))
    End Function
    '
    ' toggleWprgmRunButton: with specific test context and state.
    '		Name : button
    ' 		Text : 
    ' 		TabIndex : 5
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function ToggleWprgmRunButtonButton(anchor As TestObject, flags As Long) As  GuiTestObject
        ToggleWprgmRunButtonButton = New GuiTestObject(GetMappedTestObject("ToggleWprgmRunButtonButton"), anchor, flags)
    End Function
	
    '
    ' _0: with default state.
    '		Name : button
    ' 		Text : 0
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : WRITE DATA
    ' 		.classIndex : 0
    '
    Protected Function _0Button() As GuiTestObject
        _0Button = New GuiTestObject(GetMappedTestObject("_0Button"))
    End Function
    '
    ' _0: with specific test context and state.
    '		Name : button
    ' 		Text : 0
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : WRITE DATA
    ' 		.classIndex : 0
    '
    Protected Function _0Button(anchor As TestObject, flags As Long) As  GuiTestObject
        _0Button = New GuiTestObject(GetMappedTestObject("_0Button"), anchor, flags)
    End Function
	
    '
    ' _1: with default state.
    '		Name : button
    ' 		Text : 1
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : DEL
    ' 		.classIndex : 0
    '
    Protected Function _1Button() As GuiTestObject
        _1Button = New GuiTestObject(GetMappedTestObject("_1Button"))
    End Function
    '
    ' _1: with specific test context and state.
    '		Name : button
    ' 		Text : 1
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : DEL
    ' 		.classIndex : 0
    '
    Protected Function _1Button(anchor As TestObject, flags As Long) As  GuiTestObject
        _1Button = New GuiTestObject(GetMappedTestObject("_1Button"), anchor, flags)
    End Function
	
    '
    ' _2: with default state.
    '		Name : button
    ' 		Text : 2
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : CL REG
    ' 		.classIndex : 0
    '
    Protected Function _2Button() As GuiTestObject
        _2Button = New GuiTestObject(GetMappedTestObject("_2Button"))
    End Function
    '
    ' _2: with specific test context and state.
    '		Name : button
    ' 		Text : 2
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : CL REG
    ' 		.classIndex : 0
    '
    Protected Function _2Button(anchor As TestObject, flags As Long) As  GuiTestObject
        _2Button = New GuiTestObject(GetMappedTestObject("_2Button"), anchor, flags)
    End Function
	
    '
    ' _3: with default state.
    '		Name : button
    ' 		Text : 3
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : CL PGRM
    ' 		.classIndex : 0
    '
    Protected Function _3Button() As GuiTestObject
        _3Button = New GuiTestObject(GetMappedTestObject("_3Button"))
    End Function
    '
    ' _3: with specific test context and state.
    '		Name : button
    ' 		Text : 3
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : CL PGRM
    ' 		.classIndex : 0
    '
    Protected Function _3Button(anchor As TestObject, flags As Long) As  GuiTestObject
        _3Button = New GuiTestObject(GetMappedTestObject("_3Button"), anchor, flags)
    End Function
	
    '
    ' _4: with default state.
    '		Name : button
    ' 		Text : 4
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : x≠0?
    ' 		.classIndex : 0
    '
    Protected Function _4Button() As GuiTestObject
        _4Button = New GuiTestObject(GetMappedTestObject("_4Button"))
    End Function
    '
    ' _4: with specific test context and state.
    '		Name : button
    ' 		Text : 4
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : x≠0?
    ' 		.classIndex : 0
    '
    Protected Function _4Button(anchor As TestObject, flags As Long) As  GuiTestObject
        _4Button = New GuiTestObject(GetMappedTestObject("_4Button"), anchor, flags)
    End Function
	
    '
    ' _5: with default state.
    '		Name : button
    ' 		Text : 5
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : x=0?
    ' 		.classIndex : 0
    '
    Protected Function _5Button() As GuiTestObject
        _5Button = New GuiTestObject(GetMappedTestObject("_5Button"))
    End Function
    '
    ' _5: with specific test context and state.
    '		Name : button
    ' 		Text : 5
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : x=0?
    ' 		.classIndex : 0
    '
    Protected Function _5Button(anchor As TestObject, flags As Long) As  GuiTestObject
        _5Button = New GuiTestObject(GetMappedTestObject("_5Button"), anchor, flags)
    End Function
	
    '
    ' _6: with default state.
    '		Name : button
    ' 		Text : 6
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : x>0?
    ' 		.classIndex : 0
    '
    Protected Function _6Button() As GuiTestObject
        _6Button = New GuiTestObject(GetMappedTestObject("_6Button"))
    End Function
    '
    ' _6: with specific test context and state.
    '		Name : button
    ' 		Text : 6
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : x>0?
    ' 		.classIndex : 0
    '
    Protected Function _6Button(anchor As TestObject, flags As Long) As  GuiTestObject
        _6Button = New GuiTestObject(GetMappedTestObject("_6Button"), anchor, flags)
    End Function
	
    '
    ' _7: with default state.
    '		Name : button
    ' 		Text : 7
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : x≠y?
    ' 		.classIndex : 0
    '
    Protected Function _7Button() As GuiTestObject
        _7Button = New GuiTestObject(GetMappedTestObject("_7Button"))
    End Function
    '
    ' _7: with specific test context and state.
    '		Name : button
    ' 		Text : 7
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : x≠y?
    ' 		.classIndex : 0
    '
    Protected Function _7Button(anchor As TestObject, flags As Long) As  GuiTestObject
        _7Button = New GuiTestObject(GetMappedTestObject("_7Button"), anchor, flags)
    End Function
	
    '
    ' _9: with default state.
    '		Name : button
    ' 		Text : 9
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : x>y?
    ' 		.classIndex : 0
    '
    Protected Function _9Button() As GuiTestObject
        _9Button = New GuiTestObject(GetMappedTestObject("_9Button"))
    End Function
    '
    ' _9: with specific test context and state.
    '		Name : button
    ' 		Text : 9
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : x>y?
    ' 		.classIndex : 0
    '
    Protected Function _9Button(anchor As TestObject, flags As Long) As  GuiTestObject
        _9Button = New GuiTestObject(GetMappedTestObject("_9Button"), anchor, flags)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_1 object in the SUT.
    '
    Protected Function numericTextBox_standard_1VP() As IFtVerificationPoint
        numericTextBox_standard_1VP = vp("numericTextBox_standard_1")
    End Function
    Protected Function numericTextBox_standard_1VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_1VP = vp("numericTextBox_standard_1", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_10 object in the SUT.
    '
    Protected Function numericTextBox_standard_10VP() As IFtVerificationPoint
        numericTextBox_standard_10VP = vp("numericTextBox_standard_10")
    End Function
    Protected Function numericTextBox_standard_10VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_10VP = vp("numericTextBox_standard_10", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_11 object in the SUT.
    '
    Protected Function numericTextBox_standard_11VP() As IFtVerificationPoint
        numericTextBox_standard_11VP = vp("numericTextBox_standard_11")
    End Function
    Protected Function numericTextBox_standard_11VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_11VP = vp("numericTextBox_standard_11", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_12 object in the SUT.
    '
    Protected Function numericTextBox_standard_12VP() As IFtVerificationPoint
        numericTextBox_standard_12VP = vp("numericTextBox_standard_12")
    End Function
    Protected Function numericTextBox_standard_12VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_12VP = vp("numericTextBox_standard_12", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_13 object in the SUT.
    '
    Protected Function numericTextBox_standard_13VP() As IFtVerificationPoint
        numericTextBox_standard_13VP = vp("numericTextBox_standard_13")
    End Function
    Protected Function numericTextBox_standard_13VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_13VP = vp("numericTextBox_standard_13", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_14 object in the SUT.
    '
    Protected Function numericTextBox_standard_14VP() As IFtVerificationPoint
        numericTextBox_standard_14VP = vp("numericTextBox_standard_14")
    End Function
    Protected Function numericTextBox_standard_14VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_14VP = vp("numericTextBox_standard_14", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_15 object in the SUT.
    '
    Protected Function numericTextBox_standard_15VP() As IFtVerificationPoint
        numericTextBox_standard_15VP = vp("numericTextBox_standard_15")
    End Function
    Protected Function numericTextBox_standard_15VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_15VP = vp("numericTextBox_standard_15", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_16 object in the SUT.
    '
    Protected Function numericTextBox_standard_16VP() As IFtVerificationPoint
        numericTextBox_standard_16VP = vp("numericTextBox_standard_16")
    End Function
    Protected Function numericTextBox_standard_16VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_16VP = vp("numericTextBox_standard_16", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_17 object in the SUT.
    '
    Protected Function numericTextBox_standard_17VP() As IFtVerificationPoint
        numericTextBox_standard_17VP = vp("numericTextBox_standard_17")
    End Function
    Protected Function numericTextBox_standard_17VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_17VP = vp("numericTextBox_standard_17", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_18 object in the SUT.
    '
    Protected Function numericTextBox_standard_18VP() As IFtVerificationPoint
        numericTextBox_standard_18VP = vp("numericTextBox_standard_18")
    End Function
    Protected Function numericTextBox_standard_18VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_18VP = vp("numericTextBox_standard_18", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_19 object in the SUT.
    '
    Protected Function numericTextBox_standard_19VP() As IFtVerificationPoint
        numericTextBox_standard_19VP = vp("numericTextBox_standard_19")
    End Function
    Protected Function numericTextBox_standard_19VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_19VP = vp("numericTextBox_standard_19", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_2 object in the SUT.
    '
    Protected Function numericTextBox_standard_2VP() As IFtVerificationPoint
        numericTextBox_standard_2VP = vp("numericTextBox_standard_2")
    End Function
    Protected Function numericTextBox_standard_2VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_2VP = vp("numericTextBox_standard_2", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_20 object in the SUT.
    '
    Protected Function numericTextBox_standard_20VP() As IFtVerificationPoint
        numericTextBox_standard_20VP = vp("numericTextBox_standard_20")
    End Function
    Protected Function numericTextBox_standard_20VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_20VP = vp("numericTextBox_standard_20", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_21 object in the SUT.
    '
    Protected Function numericTextBox_standard_21VP() As IFtVerificationPoint
        numericTextBox_standard_21VP = vp("numericTextBox_standard_21")
    End Function
    Protected Function numericTextBox_standard_21VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_21VP = vp("numericTextBox_standard_21", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_22 object in the SUT.
    '
    Protected Function numericTextBox_standard_22VP() As IFtVerificationPoint
        numericTextBox_standard_22VP = vp("numericTextBox_standard_22")
    End Function
    Protected Function numericTextBox_standard_22VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_22VP = vp("numericTextBox_standard_22", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_23 object in the SUT.
    '
    Protected Function numericTextBox_standard_23VP() As IFtVerificationPoint
        numericTextBox_standard_23VP = vp("numericTextBox_standard_23")
    End Function
    Protected Function numericTextBox_standard_23VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_23VP = vp("numericTextBox_standard_23", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_24 object in the SUT.
    '
    Protected Function numericTextBox_standard_24VP() As IFtVerificationPoint
        numericTextBox_standard_24VP = vp("numericTextBox_standard_24")
    End Function
    Protected Function numericTextBox_standard_24VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_24VP = vp("numericTextBox_standard_24", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_25 object in the SUT.
    '
    Protected Function numericTextBox_standard_25VP() As IFtVerificationPoint
        numericTextBox_standard_25VP = vp("numericTextBox_standard_25")
    End Function
    Protected Function numericTextBox_standard_25VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_25VP = vp("numericTextBox_standard_25", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_26 object in the SUT.
    '
    Protected Function numericTextBox_standard_26VP() As IFtVerificationPoint
        numericTextBox_standard_26VP = vp("numericTextBox_standard_26")
    End Function
    Protected Function numericTextBox_standard_26VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_26VP = vp("numericTextBox_standard_26", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_3 object in the SUT.
    '
    Protected Function numericTextBox_standard_3VP() As IFtVerificationPoint
        numericTextBox_standard_3VP = vp("numericTextBox_standard_3")
    End Function
    Protected Function numericTextBox_standard_3VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_3VP = vp("numericTextBox_standard_3", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_4 object in the SUT.
    '
    Protected Function numericTextBox_standard_4VP() As IFtVerificationPoint
        numericTextBox_standard_4VP = vp("numericTextBox_standard_4")
    End Function
    Protected Function numericTextBox_standard_4VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_4VP = vp("numericTextBox_standard_4", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_5 object in the SUT.
    '
    Protected Function numericTextBox_standard_5VP() As IFtVerificationPoint
        numericTextBox_standard_5VP = vp("numericTextBox_standard_5")
    End Function
    Protected Function numericTextBox_standard_5VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_5VP = vp("numericTextBox_standard_5", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_6 object in the SUT.
    '
    Protected Function numericTextBox_standard_6VP() As IFtVerificationPoint
        numericTextBox_standard_6VP = vp("numericTextBox_standard_6")
    End Function
    Protected Function numericTextBox_standard_6VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_6VP = vp("numericTextBox_standard_6", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_7 object in the SUT.
    '
    Protected Function numericTextBox_standard_7VP() As IFtVerificationPoint
        numericTextBox_standard_7VP = vp("numericTextBox_standard_7")
    End Function
    Protected Function numericTextBox_standard_7VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_7VP = vp("numericTextBox_standard_7", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_8 object in the SUT.
    '
    Protected Function numericTextBox_standard_8VP() As IFtVerificationPoint
        numericTextBox_standard_8VP = vp("numericTextBox_standard_8")
    End Function
    Protected Function numericTextBox_standard_8VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_8VP = vp("numericTextBox_standard_8", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_9 object in the SUT.
    '
    Protected Function numericTextBox_standard_9VP() As IFtVerificationPoint
        numericTextBox_standard_9VP = vp("numericTextBox_standard_9")
    End Function
    Protected Function numericTextBox_standard_9VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_9VP = vp("numericTextBox_standard_9", anchor)
    End Function
	
    

    Protected Sub New()
        Dim ISI As Rational.Test.Ft.Script.Impl.IScriptInternal = Me
        ISI.SetScriptName("HP97p35p39")
    End Sub
End Class
	

#End Region

