#Region " DO NOT EDIT: This file is automatically generated "

'Only the associated template file should be edited directly.
'Helper class files are automatically regenerated from the template
'files at various times, including record actions and test object
'insertion actions.  Any changes made directly to a helper class
'file will be lost when automatically updated.

Imports Rational.Test.Ft.Object.Interfaces
Imports Rational.Test.Ft.Script
Imports Rational.Test.Ft.Vp



'Script Name   : HP97p18p19
'Generated     : 2007/06/24 11:11:24 PM
'Description   : Helper class for script
'Original Host : Windows XP x86 5.1 build 2600 Service Pack 2
 
'since  June 24, 2007
'author phl
 
Public MustInherit Class HP97p18p19Helper 
    Inherits RationalTestScript
    
    '
    ' A: with default state.
    '		Name : button
    ' 		Text : A
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : a
    ' 		.classIndex : 0
    '
    Protected Function AButton() As GuiTestObject
        AButton = New GuiTestObject(GetMappedTestObject("AButton"))
    End Function
    '
    ' A: with specific test context and state.
    '		Name : button
    ' 		Text : A
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : a
    ' 		.classIndex : 0
    '
    Protected Function AButton(anchor As TestObject, flags As Long) As  GuiTestObject
        AButton = New GuiTestObject(GetMappedTestObject("AButton"), anchor, flags)
    End Function
	
    '
    ' Div: with default state.
    '		Name : button
    ' 		Text : ÷
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : π
    ' 		.classIndex : 0
    '
    Protected Function DivButton() As GuiTestObject
        DivButton = New GuiTestObject(GetMappedTestObject("DivButton"))
    End Function
    '
    ' Div: with specific test context and state.
    '		Name : button
    ' 		Text : ÷
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : π
    ' 		.classIndex : 0
    '
    Protected Function DivButton(anchor As TestObject, flags As Long) As  GuiTestObject
        DivButton = New GuiTestObject(GetMappedTestObject("DivButton"), anchor, flags)
    End Function
	
    '
    ' f: with default state.
    '		Name : button
    ' 		Text : f
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function FButton() As GuiTestObject
        FButton = New GuiTestObject(GetMappedTestObject("FButton"))
    End Function
    '
    ' f: with specific test context and state.
    '		Name : button
    ' 		Text : f
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function FButton(anchor As TestObject, flags As Long) As  GuiTestObject
        FButton = New GuiTestObject(GetMappedTestObject("FButton"), anchor, flags)
    End Function
	
    '
    ' HP97: with default state.
    '		Name : HP97
    ' 		Text : HP97
    ' 		TabIndex : 0
    ' 		.class : Mockingbird.HP.HP97.HP97
    ' 		.processName : Mockingbird.HP.HP97.exe
    '
    Protected Function HP97Window() As TopLevelSubitemTestObject
        HP97Window = New TopLevelSubitemTestObject(GetMappedTestObject("HP97Window"))
    End Function
    '
    ' HP97: with specific test context and state.
    '		Name : HP97
    ' 		Text : HP97
    ' 		TabIndex : 0
    ' 		.class : Mockingbird.HP.HP97.HP97
    ' 		.processName : Mockingbird.HP.HP97.exe
    '
    Protected Function HP97Window(anchor As TestObject, flags As Long) As  TopLevelSubitemTestObject
        HP97Window = New TopLevelSubitemTestObject(GetMappedTestObject("HP97Window"), anchor, flags)
    End Function
	
    '
    ' LBL: with default state.
    '		Name : button
    ' 		Text : LBL
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : STF
    ' 		.classIndex : 0
    '
    Protected Function LBLButton() As GuiTestObject
        LBLButton = New GuiTestObject(GetMappedTestObject("LBLButton"))
    End Function
    '
    ' LBL: with specific test context and state.
    '		Name : button
    ' 		Text : LBL
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : STF
    ' 		.classIndex : 0
    '
    Protected Function LBLButton(anchor As TestObject, flags As Long) As  GuiTestObject
        LBLButton = New GuiTestObject(GetMappedTestObject("LBLButton"), anchor, flags)
    End Function
	
    '
    ' menuStrip: with default state.
    '		Name : menuStrip
    ' 		TabIndex : 6
    ' 		.class : System.Windows.Forms.MenuStrip
    ' 		.classIndex : 0
    '
    Protected Function MenuStripMenuBar() As GuiSubitemTestObject
        MenuStripMenuBar = New GuiSubitemTestObject(GetMappedTestObject("MenuStripMenuBar"))
    End Function
    '
    ' menuStrip: with specific test context and state.
    '		Name : menuStrip
    ' 		TabIndex : 6
    ' 		.class : System.Windows.Forms.MenuStrip
    ' 		.classIndex : 0
    '
    Protected Function MenuStripMenuBar(anchor As TestObject, flags As Long) As  GuiSubitemTestObject
        MenuStripMenuBar = New GuiSubitemTestObject(GetMappedTestObject("MenuStripMenuBar"), anchor, flags)
    End Function
	
    '
    ' Mult: with default state.
    '		Name : button
    ' 		Text : ×
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : x≤y?
    ' 		.classIndex : 0
    '
    Protected Function MultButton() As GuiTestObject
        MultButton = New GuiTestObject(GetMappedTestObject("MultButton"))
    End Function
    '
    ' Mult: with specific test context and state.
    '		Name : button
    ' 		Text : ×
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : x≤y?
    ' 		.classIndex : 0
    '
    Protected Function MultButton(anchor As TestObject, flags As Long) As  GuiTestObject
        MultButton = New GuiTestObject(GetMappedTestObject("MultButton"), anchor, flags)
    End Function
	
    '
    ' MyDocuments: with default state.
    '		.class : .Pushbutton
    ' 		.name : My Documents
    ' 		.classIndex : 2
    '
    Protected Function MyDocumentsButton() As GuiTestObject
        MyDocumentsButton = New GuiTestObject(GetMappedTestObject("MyDocumentsButton"))
    End Function
    '
    ' MyDocuments: with specific test context and state.
    '		.class : .Pushbutton
    ' 		.name : My Documents
    ' 		.classIndex : 2
    '
    Protected Function MyDocumentsButton(anchor As TestObject, flags As Long) As  GuiTestObject
        MyDocumentsButton = New GuiTestObject(GetMappedTestObject("MyDocumentsButton"), anchor, flags)
    End Function
	
    '
    ' numericTextBox: with default state.
    '		Name : numericTextBox
    ' 		TabIndex : 0
    ' 		.class : System.Windows.Forms.TextBox
    ' 		.classIndex : 0
    '
    Protected Function NumericTextBoxText() As TextGuiSubitemTestObject
        NumericTextBoxText = New TextGuiSubitemTestObject(GetMappedTestObject("NumericTextBoxText"))
    End Function
    '
    ' numericTextBox: with specific test context and state.
    '		Name : numericTextBox
    ' 		TabIndex : 0
    ' 		.class : System.Windows.Forms.TextBox
    ' 		.classIndex : 0
    '
    Protected Function NumericTextBoxText(anchor As TestObject, flags As Long) As  TextGuiSubitemTestObject
        NumericTextBoxText = New TextGuiSubitemTestObject(GetMappedTestObject("NumericTextBoxText"), anchor, flags)
    End Function
	
    '
    ' PRINTX: with default state.
    '		Name : button
    ' 		Text : PRINT x
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : STACK
    ' 		.classIndex : 0
    '
    Protected Function PRINTXButton() As GuiTestObject
        PRINTXButton = New GuiTestObject(GetMappedTestObject("PRINTXButton"))
    End Function
    '
    ' PRINTX: with specific test context and state.
    '		Name : button
    ' 		Text : PRINT x
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : STACK
    ' 		.classIndex : 0
    '
    Protected Function PRINTXButton(anchor As TestObject, flags As Long) As  GuiTestObject
        PRINTXButton = New GuiTestObject(GetMappedTestObject("PRINTXButton"), anchor, flags)
    End Function
	
    '
    ' RTN: with default state.
    '		Name : button
    ' 		Text : RTN
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : RND
    ' 		.classIndex : 0
    '
    Protected Function RTNButton() As GuiTestObject
        RTNButton = New GuiTestObject(GetMappedTestObject("RTNButton"))
    End Function
    '
    ' RTN: with specific test context and state.
    '		Name : button
    ' 		Text : RTN
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : RND
    ' 		.classIndex : 0
    '
    Protected Function RTNButton(anchor As TestObject, flags As Long) As  GuiTestObject
        RTNButton = New GuiTestObject(GetMappedTestObject("RTNButton"), anchor, flags)
    End Function
	
    '
    ' SaveAs: with default state.
    '		.text : Save As
    ' 		.class : #32770
    ' 		.processName : Mockingbird.HP.HP97.exe
    '
    Protected Function SaveAsWindow() As TopLevelSubitemTestObject
        SaveAsWindow = New TopLevelSubitemTestObject(GetMappedTestObject("SaveAsWindow"))
    End Function
    '
    ' SaveAs: with specific test context and state.
    '		.text : Save As
    ' 		.class : #32770
    ' 		.processName : Mockingbird.HP.HP97.exe
    '
    Protected Function SaveAsWindow(anchor As TestObject, flags As Long) As  TopLevelSubitemTestObject
        SaveAsWindow = New TopLevelSubitemTestObject(GetMappedTestObject("SaveAsWindow"), anchor, flags)
    End Function
	
    '
    ' Save: with default state.
    '		.class : .Pushbutton
    ' 		.name : Save
    ' 		.classIndex : 0
    '
    Protected Function SaveButton() As GuiTestObject
        SaveButton = New GuiTestObject(GetMappedTestObject("SaveButton"))
    End Function
    '
    ' Save: with specific test context and state.
    '		.class : .Pushbutton
    ' 		.name : Save
    ' 		.classIndex : 0
    '
    Protected Function SaveButton(anchor As TestObject, flags As Long) As  GuiTestObject
        SaveButton = New GuiTestObject(GetMappedTestObject("SaveButton"), anchor, flags)
    End Function
	
    '
    ' Square: with default state.
    '		Name : button
    ' 		Text : x²
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : x̅
    ' 		.classIndex : 0
    '
    Protected Function SquareButton() As GuiTestObject
        SquareButton = New GuiTestObject(GetMappedTestObject("SquareButton"))
    End Function
    '
    ' Square: with specific test context and state.
    '		Name : button
    ' 		Text : x²
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : x̅
    ' 		.classIndex : 0
    '
    Protected Function SquareButton(anchor As TestObject, flags As Long) As  GuiTestObject
        SquareButton = New GuiTestObject(GetMappedTestObject("SquareButton"), anchor, flags)
    End Function
	
    '
    ' titleTextBox: with default state.
    '		Name : titleTextBox
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.TextBox
    ' 		.classIndex : 0
    '
    Protected Function TitleTextBoxText() As TextGuiSubitemTestObject
        TitleTextBoxText = New TextGuiSubitemTestObject(GetMappedTestObject("TitleTextBoxText"))
    End Function
    '
    ' titleTextBox: with specific test context and state.
    '		Name : titleTextBox
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.TextBox
    ' 		.classIndex : 0
    '
    Protected Function TitleTextBoxText(anchor As TestObject, flags As Long) As  TextGuiSubitemTestObject
        TitleTextBoxText = New TextGuiSubitemTestObject(GetMappedTestObject("TitleTextBoxText"), anchor, flags)
    End Function
	
    '
    ' _0: with default state.
    '		Name : button
    ' 		Text : 0
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : WRITE DATA
    ' 		.classIndex : 0
    '
    Protected Function _0Button() As GuiTestObject
        _0Button = New GuiTestObject(GetMappedTestObject("_0Button"))
    End Function
    '
    ' _0: with specific test context and state.
    '		Name : button
    ' 		Text : 0
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : WRITE DATA
    ' 		.classIndex : 0
    '
    Protected Function _0Button(anchor As TestObject, flags As Long) As  GuiTestObject
        _0Button = New GuiTestObject(GetMappedTestObject("_0Button"), anchor, flags)
    End Function
	
    '
    ' _1: with default state.
    '		Name : button
    ' 		Text : 1
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : DEL
    ' 		.classIndex : 0
    '
    Protected Function _1Button() As GuiTestObject
        _1Button = New GuiTestObject(GetMappedTestObject("_1Button"))
    End Function
    '
    ' _1: with specific test context and state.
    '		Name : button
    ' 		Text : 1
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : DEL
    ' 		.classIndex : 0
    '
    Protected Function _1Button(anchor As TestObject, flags As Long) As  GuiTestObject
        _1Button = New GuiTestObject(GetMappedTestObject("_1Button"), anchor, flags)
    End Function
	
    '
    ' _2: with default state.
    '		Name : button
    ' 		Text : 2
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : CL REG
    ' 		.classIndex : 0
    '
    Protected Function _2Button() As GuiTestObject
        _2Button = New GuiTestObject(GetMappedTestObject("_2Button"))
    End Function
    '
    ' _2: with specific test context and state.
    '		Name : button
    ' 		Text : 2
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : CL REG
    ' 		.classIndex : 0
    '
    Protected Function _2Button(anchor As TestObject, flags As Long) As  GuiTestObject
        _2Button = New GuiTestObject(GetMappedTestObject("_2Button"), anchor, flags)
    End Function
	
    '
    ' _3: with default state.
    '		Name : button
    ' 		Text : 3
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : CL PGRM
    ' 		.classIndex : 0
    '
    Protected Function _3Button() As GuiTestObject
        _3Button = New GuiTestObject(GetMappedTestObject("_3Button"))
    End Function
    '
    ' _3: with specific test context and state.
    '		Name : button
    ' 		Text : 3
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : CL PGRM
    ' 		.classIndex : 0
    '
    Protected Function _3Button(anchor As TestObject, flags As Long) As  GuiTestObject
        _3Button = New GuiTestObject(GetMappedTestObject("_3Button"), anchor, flags)
    End Function
	
    '
    ' _5: with default state.
    '		Name : button
    ' 		Text : 5
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : x=0?
    ' 		.classIndex : 0
    '
    Protected Function _5Button() As GuiTestObject
        _5Button = New GuiTestObject(GetMappedTestObject("_5Button"))
    End Function
    '
    ' _5: with specific test context and state.
    '		Name : button
    ' 		Text : 5
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : x=0?
    ' 		.classIndex : 0
    '
    Protected Function _5Button(anchor As TestObject, flags As Long) As  GuiTestObject
        _5Button = New GuiTestObject(GetMappedTestObject("_5Button"), anchor, flags)
    End Function
	
    '
    ' _9: with default state.
    '		Name : button
    ' 		Text : 9
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : x>y?
    ' 		.classIndex : 0
    '
    Protected Function _9Button() As GuiTestObject
        _9Button = New GuiTestObject(GetMappedTestObject("_9Button"))
    End Function
    '
    ' _9: with specific test context and state.
    '		Name : button
    ' 		Text : 9
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : x>y?
    ' 		.classIndex : 0
    '
    Protected Function _9Button(anchor As TestObject, flags As Long) As  GuiTestObject
        _9Button = New GuiTestObject(GetMappedTestObject("_9Button"), anchor, flags)
    End Function
	
    '
    ' toggleWprgmRunButton: with default state.
    '		Name : button
    ' 		Text : 
    ' 		TabIndex : 5
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function toggleWpgrmRunButton() As GuiTestObject
        toggleWpgrmRunButton = New GuiTestObject(GetMappedTestObject("toggleWpgrmRunButton"))
    End Function
    '
    ' toggleWprgmRunButton: with specific test context and state.
    '		Name : button
    ' 		Text : 
    ' 		TabIndex : 5
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function toggleWpgrmRunButton(anchor As TestObject, flags As Long) As  GuiTestObject
        toggleWpgrmRunButton = New GuiTestObject(GetMappedTestObject("toggleWpgrmRunButton"), anchor, flags)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_1 object in the SUT.
    '
    Protected Function numericTextBox_standard_1VP() As IFtVerificationPoint
        numericTextBox_standard_1VP = vp("numericTextBox_standard_1")
    End Function
    Protected Function numericTextBox_standard_1VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_1VP = vp("numericTextBox_standard_1", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_2 object in the SUT.
    '
    Protected Function numericTextBox_standard_2VP() As IFtVerificationPoint
        numericTextBox_standard_2VP = vp("numericTextBox_standard_2")
    End Function
    Protected Function numericTextBox_standard_2VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_2VP = vp("numericTextBox_standard_2", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_3 object in the SUT.
    '
    Protected Function numericTextBox_standard_3VP() As IFtVerificationPoint
        numericTextBox_standard_3VP = vp("numericTextBox_standard_3")
    End Function
    Protected Function numericTextBox_standard_3VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_3VP = vp("numericTextBox_standard_3", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_4 object in the SUT.
    '
    Protected Function numericTextBox_standard_4VP() As IFtVerificationPoint
        numericTextBox_standard_4VP = vp("numericTextBox_standard_4")
    End Function
    Protected Function numericTextBox_standard_4VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_4VP = vp("numericTextBox_standard_4", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_5 object in the SUT.
    '
    Protected Function numericTextBox_standard_5VP() As IFtVerificationPoint
        numericTextBox_standard_5VP = vp("numericTextBox_standard_5")
    End Function
    Protected Function numericTextBox_standard_5VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_5VP = vp("numericTextBox_standard_5", anchor)
    End Function
	
    

    Protected Sub New()
        Dim ISI As Rational.Test.Ft.Script.Impl.IScriptInternal = Me
        ISI.SetScriptName("HP97p18p19")
    End Sub
End Class
	

#End Region

