#Region " DO NOT EDIT: This file is automatically generated "

'Only the associated template file should be edited directly.
'Helper class files are automatically regenerated from the template
'files at various times, including record actions and test object
'insertion actions.  Any changes made directly to a helper class
'file will be lost when automatically updated.

Imports Rational.Test.Ft.Object.Interfaces
Imports Rational.Test.Ft.Script
Imports Rational.Test.Ft.Vp



'Script Name   : HP97p15p17
'Generated     : 2007/06/20 8:27:59 PM
'Description   : Helper class for script
'Original Host : Windows XP x86 5.1 build 2600 Service Pack 2
 
'since  June 20, 2007
'author phl
 
Public MustInherit Class HP97p15p17Helper 
    Inherits RationalTestScript
    
    '
    ' A: with default state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : A
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : a
    ' 		.classIndex : 0
    '
    Protected Function AButton() As GuiTestObject
        AButton = New GuiTestObject(GetMappedTestObject("AButton"))
    End Function
    '
    ' A: with specific test context and state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : A
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : a
    ' 		.classIndex : 0
    '
    Protected Function AButton(anchor As TestObject, flags As Long) As  GuiTestObject
        AButton = New GuiTestObject(GetMappedTestObject("AButton"), anchor, flags)
    End Function
	
    '
    ' B: with default state.
    '		Name : button
    ' 		Text : B
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : b
    ' 		.classIndex : 0
    '
    Protected Function BButton() As GuiTestObject
        BButton = New GuiTestObject(GetMappedTestObject("BButton"))
    End Function
    '
    ' B: with specific test context and state.
    '		Name : button
    ' 		Text : B
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : b
    ' 		.classIndex : 0
    '
    Protected Function BButton(anchor As TestObject, flags As Long) As  GuiTestObject
        BButton = New GuiTestObject(GetMappedTestObject("BButton"), anchor, flags)
    End Function
	
    '
    ' C: with default state.
    '		Name : button
    ' 		Text : C
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : c
    ' 		.classIndex : 0
    '
    Protected Function CButton() As GuiTestObject
        CButton = New GuiTestObject(GetMappedTestObject("CButton"))
    End Function
    '
    ' C: with specific test context and state.
    '		Name : button
    ' 		Text : C
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : c
    ' 		.classIndex : 0
    '
    Protected Function CButton(anchor As TestObject, flags As Long) As  GuiTestObject
        CButton = New GuiTestObject(GetMappedTestObject("CButton"), anchor, flags)
    End Function
	
    '
    ' FolderView: with default state.
    '		.class : SysListView32
    ' 		.classIndex : 0
    '
    Protected Function FolderViewTable() As SelectGuiSubitemTestObject
        FolderViewTable = New SelectGuiSubitemTestObject(GetMappedTestObject("FolderViewTable"))
    End Function
    '
    ' FolderView: with specific test context and state.
    '		.class : SysListView32
    ' 		.classIndex : 0
    '
    Protected Function FolderViewTable(anchor As TestObject, flags As Long) As  SelectGuiSubitemTestObject
        FolderViewTable = New SelectGuiSubitemTestObject(GetMappedTestObject("FolderViewTable"), anchor, flags)
    End Function
	
    '
    ' HP97: with default state.
    '		Name : HP97
    ' 		TabIndex : 0
    ' 		Text : HP97
    ' 		.class : Mockingbird.HP.HP97.HP97
    ' 		.processName : Mockingbird.HP.HP97.exe
    '
    Protected Function HP97Window() As TopLevelSubitemTestObject
        HP97Window = New TopLevelSubitemTestObject(GetMappedTestObject("HP97Window"))
    End Function
    '
    ' HP97: with specific test context and state.
    '		Name : HP97
    ' 		TabIndex : 0
    ' 		Text : HP97
    ' 		.class : Mockingbird.HP.HP97.HP97
    ' 		.processName : Mockingbird.HP.HP97.exe
    '
    Protected Function HP97Window(anchor As TestObject, flags As Long) As  TopLevelSubitemTestObject
        HP97Window = New TopLevelSubitemTestObject(GetMappedTestObject("HP97Window"), anchor, flags)
    End Function
	
    '
    ' menuStrip: with default state.
    '		Name : menuStrip
    ' 		TabIndex : 6
    ' 		.class : System.Windows.Forms.MenuStrip
    ' 		.classIndex : 0
    '
    Protected Function MenuStripMenuBar() As GuiSubitemTestObject
        MenuStripMenuBar = New GuiSubitemTestObject(GetMappedTestObject("MenuStripMenuBar"))
    End Function
    '
    ' menuStrip: with specific test context and state.
    '		Name : menuStrip
    ' 		TabIndex : 6
    ' 		.class : System.Windows.Forms.MenuStrip
    ' 		.classIndex : 0
    '
    Protected Function MenuStripMenuBar(anchor As TestObject, flags As Long) As  GuiSubitemTestObject
        MenuStripMenuBar = New GuiSubitemTestObject(GetMappedTestObject("MenuStripMenuBar"), anchor, flags)
    End Function
	
    '
    ' MyComputer: with default state.
    '		.class : .Pushbutton
    ' 		.name : My Computer
    ' 		.classIndex : 3
    '
    Protected Function MyComputerButton() As GuiTestObject
        MyComputerButton = New GuiTestObject(GetMappedTestObject("MyComputerButton"))
    End Function
    '
    ' MyComputer: with specific test context and state.
    '		.class : .Pushbutton
    ' 		.name : My Computer
    ' 		.classIndex : 3
    '
    Protected Function MyComputerButton(anchor As TestObject, flags As Long) As  GuiTestObject
        MyComputerButton = New GuiTestObject(GetMappedTestObject("MyComputerButton"), anchor, flags)
    End Function
	
    '
    ' MyDocuments: with default state.
    '		.class : .Pushbutton
    ' 		.name : My Documents
    ' 		.classIndex : 2
    '
    Protected Function MyDocumentsButton() As GuiTestObject
        MyDocumentsButton = New GuiTestObject(GetMappedTestObject("MyDocumentsButton"))
    End Function
    '
    ' MyDocuments: with specific test context and state.
    '		.class : .Pushbutton
    ' 		.name : My Documents
    ' 		.classIndex : 2
    '
    Protected Function MyDocumentsButton(anchor As TestObject, flags As Long) As  GuiTestObject
        MyDocumentsButton = New GuiTestObject(GetMappedTestObject("MyDocumentsButton"), anchor, flags)
    End Function
	
    '
    ' numericTextBox: with default state.
    '		Name : numericTextBox
    ' 		TabIndex : 0
    ' 		.class : System.Windows.Forms.TextBox
    ' 		.classIndex : 0
    '
    Protected Function NumericTextBoxText() As TextGuiSubitemTestObject
        NumericTextBoxText = New TextGuiSubitemTestObject(GetMappedTestObject("NumericTextBoxText"))
    End Function
    '
    ' numericTextBox: with specific test context and state.
    '		Name : numericTextBox
    ' 		TabIndex : 0
    ' 		.class : System.Windows.Forms.TextBox
    ' 		.classIndex : 0
    '
    Protected Function NumericTextBoxText(anchor As TestObject, flags As Long) As  TextGuiSubitemTestObject
        NumericTextBoxText = New TextGuiSubitemTestObject(GetMappedTestObject("NumericTextBoxText"), anchor, flags)
    End Function
	
    '
    ' Open: with default state.
    '		.class : .Pushbutton
    ' 		.name : Open
    ' 		.classIndex : 0
    '
    Protected Function OpenButton() As GuiTestObject
        OpenButton = New GuiTestObject(GetMappedTestObject("OpenButton"))
    End Function
    '
    ' Open: with specific test context and state.
    '		.class : .Pushbutton
    ' 		.name : Open
    ' 		.classIndex : 0
    '
    Protected Function OpenButton(anchor As TestObject, flags As Long) As  GuiTestObject
        OpenButton = New GuiTestObject(GetMappedTestObject("OpenButton"), anchor, flags)
    End Function
	
    '
    ' OpenComboBox: with default state.
    '		.text : Files of type:
    ' 		.class : ComboBox
    ' 		.classIndex : 1
    '
    Protected Function OpenComboBox() As TextSelectGuiSubitemTestObject
        OpenComboBox = New TextSelectGuiSubitemTestObject(GetMappedTestObject("OpenComboBox"))
    End Function
    '
    ' OpenComboBox: with specific test context and state.
    '		.text : Files of type:
    ' 		.class : ComboBox
    ' 		.classIndex : 1
    '
    Protected Function OpenComboBox(anchor As TestObject, flags As Long) As  TextSelectGuiSubitemTestObject
        OpenComboBox = New TextSelectGuiSubitemTestObject(GetMappedTestObject("OpenComboBox"), anchor, flags)
    End Function
	
    '
    ' Period: with default state.
    '		Name : button
    ' 		Text :  ・
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : MERGE
    ' 		.classIndex : 0
    '
    Protected Function PeriodButton() As GuiTestObject
        PeriodButton = New GuiTestObject(GetMappedTestObject("PeriodButton"))
    End Function
    '
    ' Period: with specific test context and state.
    '		Name : button
    ' 		Text :  ・
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : MERGE
    ' 		.classIndex : 0
    '
    Protected Function PeriodButton(anchor As TestObject, flags As Long) As  GuiTestObject
        PeriodButton = New GuiTestObject(GetMappedTestObject("PeriodButton"), anchor, flags)
    End Function
	
    '
    ' toggleManTraceNorm: with default state.
    '		Name : button
    ' 		TabIndex : 5
    ' 		Text : 
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : TRACE
    ' 		.classIndex : 0
    '
    Protected Function ToggleManTraceNormButton() As GuiTestObject
        ToggleManTraceNormButton = New GuiTestObject(GetMappedTestObject("ToggleManTraceNormButton"))
    End Function
    '
    ' toggleManTraceNorm: with specific test context and state.
    '		Name : button
    ' 		TabIndex : 5
    ' 		Text : 
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : TRACE
    ' 		.classIndex : 0
    '
    Protected Function ToggleManTraceNormButton(anchor As TestObject, flags As Long) As  GuiTestObject
        ToggleManTraceNormButton = New GuiTestObject(GetMappedTestObject("ToggleManTraceNormButton"), anchor, flags)
    End Function
	
    '
    ' _0: with default state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : 0
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : WRITE DATA
    ' 		.classIndex : 0
    '
    Protected Function _0Button() As GuiTestObject
        _0Button = New GuiTestObject(GetMappedTestObject("_0Button"))
    End Function
    '
    ' _0: with specific test context and state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : 0
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : WRITE DATA
    ' 		.classIndex : 0
    '
    Protected Function _0Button(anchor As TestObject, flags As Long) As  GuiTestObject
        _0Button = New GuiTestObject(GetMappedTestObject("_0Button"), anchor, flags)
    End Function
	
    '
    ' _1: with default state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : DEL
    ' 		.classIndex : 0
    '
    Protected Function _1Button() As GuiTestObject
        _1Button = New GuiTestObject(GetMappedTestObject("_1Button"))
    End Function
    '
    ' _1: with specific test context and state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : DEL
    ' 		.classIndex : 0
    '
    Protected Function _1Button(anchor As TestObject, flags As Long) As  GuiTestObject
        _1Button = New GuiTestObject(GetMappedTestObject("_1Button"), anchor, flags)
    End Function
	
    '
    ' _2: with default state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : 2
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : CL REG
    ' 		.classIndex : 0
    '
    Protected Function _2Button() As GuiTestObject
        _2Button = New GuiTestObject(GetMappedTestObject("_2Button"))
    End Function
    '
    ' _2: with specific test context and state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : 2
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : CL REG
    ' 		.classIndex : 0
    '
    Protected Function _2Button(anchor As TestObject, flags As Long) As  GuiTestObject
        _2Button = New GuiTestObject(GetMappedTestObject("_2Button"), anchor, flags)
    End Function
	
    '
    ' _3: with default state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : 3
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : CL PGRM
    ' 		.classIndex : 0
    '
    Protected Function _3Button() As GuiTestObject
        _3Button = New GuiTestObject(GetMappedTestObject("_3Button"))
    End Function
    '
    ' _3: with specific test context and state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : 3
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : CL PGRM
    ' 		.classIndex : 0
    '
    Protected Function _3Button(anchor As TestObject, flags As Long) As  GuiTestObject
        _3Button = New GuiTestObject(GetMappedTestObject("_3Button"), anchor, flags)
    End Function
	
    '
    ' _4: with default state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : 4
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : x≠0?
    ' 		.classIndex : 0
    '
    Protected Function _4Button() As GuiTestObject
        _4Button = New GuiTestObject(GetMappedTestObject("_4Button"))
    End Function
    '
    ' _4: with specific test context and state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : 4
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : x≠0?
    ' 		.classIndex : 0
    '
    Protected Function _4Button(anchor As TestObject, flags As Long) As  GuiTestObject
        _4Button = New GuiTestObject(GetMappedTestObject("_4Button"), anchor, flags)
    End Function
	
    '
    ' _5: with default state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : 5
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : x=0?
    ' 		.classIndex : 0
    '
    Protected Function _5Button() As GuiTestObject
        _5Button = New GuiTestObject(GetMappedTestObject("_5Button"))
    End Function
    '
    ' _5: with specific test context and state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : 5
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : x=0?
    ' 		.classIndex : 0
    '
    Protected Function _5Button(anchor As TestObject, flags As Long) As  GuiTestObject
        _5Button = New GuiTestObject(GetMappedTestObject("_5Button"), anchor, flags)
    End Function
	
    '
    ' _7: with default state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : 7
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : x≠y?
    ' 		.classIndex : 0
    '
    Protected Function _7Button() As GuiTestObject
        _7Button = New GuiTestObject(GetMappedTestObject("_7Button"))
    End Function
    '
    ' _7: with specific test context and state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : 7
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : x≠y?
    ' 		.classIndex : 0
    '
    Protected Function _7Button(anchor As TestObject, flags As Long) As  GuiTestObject
        _7Button = New GuiTestObject(GetMappedTestObject("_7Button"), anchor, flags)
    End Function
	
    '
    ' _9: with default state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : 9
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : x>y?
    ' 		.classIndex : 0
    '
    Protected Function _9Button() As GuiTestObject
        _9Button = New GuiTestObject(GetMappedTestObject("_9Button"))
    End Function
    '
    ' _9: with specific test context and state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : 9
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : x>y?
    ' 		.classIndex : 0
    '
    Protected Function _9Button(anchor As TestObject, flags As Long) As  GuiTestObject
        _9Button = New GuiTestObject(GetMappedTestObject("_9Button"), anchor, flags)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_1 object in the SUT.
    '
    Protected Function numericTextBox_standard_1VP() As IFtVerificationPoint
        numericTextBox_standard_1VP = vp("numericTextBox_standard_1")
    End Function
    Protected Function numericTextBox_standard_1VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_1VP = vp("numericTextBox_standard_1", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_2 object in the SUT.
    '
    Protected Function numericTextBox_standard_2VP() As IFtVerificationPoint
        numericTextBox_standard_2VP = vp("numericTextBox_standard_2")
    End Function
    Protected Function numericTextBox_standard_2VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_2VP = vp("numericTextBox_standard_2", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_3 object in the SUT.
    '
    Protected Function numericTextBox_standard_3VP() As IFtVerificationPoint
        numericTextBox_standard_3VP = vp("numericTextBox_standard_3")
    End Function
    Protected Function numericTextBox_standard_3VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_3VP = vp("numericTextBox_standard_3", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_4 object in the SUT.
    '
    Protected Function numericTextBox_standard_4VP() As IFtVerificationPoint
        numericTextBox_standard_4VP = vp("numericTextBox_standard_4")
    End Function
    Protected Function numericTextBox_standard_4VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_4VP = vp("numericTextBox_standard_4", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_5 object in the SUT.
    '
    Protected Function numericTextBox_standard_5VP() As IFtVerificationPoint
        numericTextBox_standard_5VP = vp("numericTextBox_standard_5")
    End Function
    Protected Function numericTextBox_standard_5VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_5VP = vp("numericTextBox_standard_5", anchor)
    End Function
	
    

    Protected Sub New()
        Dim ISI As Rational.Test.Ft.Script.Impl.IScriptInternal = Me
        ISI.SetScriptName("HP97p15p17")
    End Sub
End Class
	

#End Region

