#Region " DO NOT EDIT: This file is automatically generated "

'Only the associated template file should be edited directly.
'Helper class files are automatically regenerated from the template
'files at various times, including record actions and test object
'insertion actions.  Any changes made directly to a helper class
'file will be lost when automatically updated.

Imports Rational.Test.Ft.Object.Interfaces
Imports Rational.Test.Ft.Script
Imports Rational.Test.Ft.Vp



'Script Name   : HP97p48p53
'Generated     : 2007/08/16 9:04:38 PM
'Description   : Helper class for script
'Original Host : Windows XP x86 5.1 build 2600 Service Pack 2
 
'since  August 16, 2007
'author phl
 
Public MustInherit Class HP97p48p53Helper 
    Inherits RationalTestScript
    
    '
    ' CLX: with default state.
    '		Name : button
    ' 		Text : CL x
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function CLXButton() As GuiTestObject
        CLXButton = New GuiTestObject(GetMappedTestObject("CLXButton"))
    End Function
    '
    ' CLX: with specific test context and state.
    '		Name : button
    ' 		Text : CL x
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function CLXButton(anchor As TestObject, flags As Long) As  GuiTestObject
        CLXButton = New GuiTestObject(GetMappedTestObject("CLXButton"), anchor, flags)
    End Function
	
    '
    ' ENTER: with default state.
    '		Name : button
    ' 		Text : ENTER ↑
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function ENTERButton() As GuiTestObject
        ENTERButton = New GuiTestObject(GetMappedTestObject("ENTERButton"))
    End Function
    '
    ' ENTER: with specific test context and state.
    '		Name : button
    ' 		Text : ENTER ↑
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function ENTERButton(anchor As TestObject, flags As Long) As  GuiTestObject
        ENTERButton = New GuiTestObject(GetMappedTestObject("ENTERButton"), anchor, flags)
    End Function
	
    '
    ' f: with default state.
    '		Name : button
    ' 		Text : f
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function FButton() As GuiTestObject
        FButton = New GuiTestObject(GetMappedTestObject("FButton"))
    End Function
    '
    ' f: with specific test context and state.
    '		Name : button
    ' 		Text : f
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function FButton(anchor As TestObject, flags As Long) As  GuiTestObject
        FButton = New GuiTestObject(GetMappedTestObject("FButton"), anchor, flags)
    End Function
	
    '
    ' groupBoxCard: with default state.
    '		Name : groupBoxCard
    ' 		Text : 
    ' 		TabIndex : 12
    ' 		.class : System.Windows.Forms.GroupBox
    ' 		.classIndex : 0
    '
    Protected Function GroupBoxCardGroupBox() As GuiTestObject
        GroupBoxCardGroupBox = New GuiTestObject(GetMappedTestObject("GroupBoxCardGroupBox"))
    End Function
    '
    ' groupBoxCard: with specific test context and state.
    '		Name : groupBoxCard
    ' 		Text : 
    ' 		TabIndex : 12
    ' 		.class : System.Windows.Forms.GroupBox
    ' 		.classIndex : 0
    '
    Protected Function GroupBoxCardGroupBox(anchor As TestObject, flags As Long) As  GuiTestObject
        GroupBoxCardGroupBox = New GuiTestObject(GetMappedTestObject("GroupBoxCardGroupBox"), anchor, flags)
    End Function
	
    '
    ' HP97: with default state.
    '		Name : HP97
    ' 		Text : HP97
    ' 		TabIndex : 0
    ' 		.class : Mockingbird.HP.HP97.HP97
    ' 		.processName : Mockingbird.HP.HP97.exe
    '
    Protected Function HP97Window() As TopLevelSubitemTestObject
        HP97Window = New TopLevelSubitemTestObject(GetMappedTestObject("HP97Window"))
    End Function
    '
    ' HP97: with specific test context and state.
    '		Name : HP97
    ' 		Text : HP97
    ' 		TabIndex : 0
    ' 		.class : Mockingbird.HP.HP97.HP97
    ' 		.processName : Mockingbird.HP.HP97.exe
    '
    Protected Function HP97Window(anchor As TestObject, flags As Long) As  TopLevelSubitemTestObject
        HP97Window = New TopLevelSubitemTestObject(GetMappedTestObject("HP97Window"), anchor, flags)
    End Function
	
    '
    ' listBox: with default state.
    '		Name : listBox
    ' 		TabIndex : 0
    ' 		.class : System.Windows.Forms.ListBox
    ' 		.classIndex : 0
    '
    Protected Function ListBoxList() As SelectGuiSubitemTestObject
        ListBoxList = New SelectGuiSubitemTestObject(GetMappedTestObject("ListBoxList"))
    End Function
    '
    ' listBox: with specific test context and state.
    '		Name : listBox
    ' 		TabIndex : 0
    ' 		.class : System.Windows.Forms.ListBox
    ' 		.classIndex : 0
    '
    Protected Function ListBoxList(anchor As TestObject, flags As Long) As  SelectGuiSubitemTestObject
        ListBoxList = New SelectGuiSubitemTestObject(GetMappedTestObject("ListBoxList"), anchor, flags)
    End Function
	
    '
    ' numericTextBox: with default state.
    '		Name : numericTextBox
    ' 		TabIndex : 0
    ' 		.class : System.Windows.Forms.TextBox
    ' 		.classIndex : 0
    '
    Protected Function NumericTextBoxText() As TextGuiSubitemTestObject
        NumericTextBoxText = New TextGuiSubitemTestObject(GetMappedTestObject("NumericTextBoxText"))
    End Function
    '
    ' numericTextBox: with specific test context and state.
    '		Name : numericTextBox
    ' 		TabIndex : 0
    ' 		.class : System.Windows.Forms.TextBox
    ' 		.classIndex : 0
    '
    Protected Function NumericTextBoxText(anchor As TestObject, flags As Long) As  TextGuiSubitemTestObject
        NumericTextBoxText = New TextGuiSubitemTestObject(GetMappedTestObject("NumericTextBoxText"), anchor, flags)
    End Function
	
    '
    ' PRINTX: with default state.
    '		Name : button
    ' 		Text : PRINT x
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function PRINTXButton() As GuiTestObject
        PRINTXButton = New GuiTestObject(GetMappedTestObject("PRINTXButton"))
    End Function
    '
    ' PRINTX: with specific test context and state.
    '		Name : button
    ' 		Text : PRINT x
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function PRINTXButton(anchor As TestObject, flags As Long) As  GuiTestObject
        PRINTXButton = New GuiTestObject(GetMappedTestObject("PRINTXButton"), anchor, flags)
    End Function
	
    '
    ' R: with default state.
    '		Name : button
    ' 		Text : R↓
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function RDownButton() As GuiTestObject
        RDownButton = New GuiTestObject(GetMappedTestObject("RDownButton"))
    End Function
    '
    ' R: with specific test context and state.
    '		Name : button
    ' 		Text : R↓
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function RDownButton(anchor As TestObject, flags As Long) As  GuiTestObject
        RDownButton = New GuiTestObject(GetMappedTestObject("RDownButton"), anchor, flags)
    End Function
	
    '
    ' _x: with default state.
    '		Name : button
    ' 		Text : √x̅
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function SqrtButton() As GuiTestObject
        SqrtButton = New GuiTestObject(GetMappedTestObject("SqrtButton"))
    End Function
    '
    ' _x: with specific test context and state.
    '		Name : button
    ' 		Text : √x̅
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function SqrtButton(anchor As TestObject, flags As Long) As  GuiTestObject
        SqrtButton = New GuiTestObject(GetMappedTestObject("SqrtButton"), anchor, flags)
    End Function
	
    '
    ' xY: with default state.
    '		Name : button
    ' 		Text : x⇄y
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function XExchangeYButton() As GuiTestObject
        XExchangeYButton = New GuiTestObject(GetMappedTestObject("XExchangeYButton"))
    End Function
    '
    ' xY: with specific test context and state.
    '		Name : button
    ' 		Text : x⇄y
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function XExchangeYButton(anchor As TestObject, flags As Long) As  GuiTestObject
        XExchangeYButton = New GuiTestObject(GetMappedTestObject("XExchangeYButton"), anchor, flags)
    End Function
	
    '
    ' _1: with default state.
    '		Name : button
    ' 		Text : 1
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function _1Button() As GuiTestObject
        _1Button = New GuiTestObject(GetMappedTestObject("_1Button"))
    End Function
    '
    ' _1: with specific test context and state.
    '		Name : button
    ' 		Text : 1
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function _1Button(anchor As TestObject, flags As Long) As  GuiTestObject
        _1Button = New GuiTestObject(GetMappedTestObject("_1Button"), anchor, flags)
    End Function
	
    '
    ' _2: with default state.
    '		Name : button
    ' 		Text : 2
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function _2Button() As GuiTestObject
        _2Button = New GuiTestObject(GetMappedTestObject("_2Button"))
    End Function
    '
    ' _2: with specific test context and state.
    '		Name : button
    ' 		Text : 2
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function _2Button(anchor As TestObject, flags As Long) As  GuiTestObject
        _2Button = New GuiTestObject(GetMappedTestObject("_2Button"), anchor, flags)
    End Function
	
    '
    ' _3: with default state.
    '		Name : button
    ' 		Text : 3
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function _3Button() As GuiTestObject
        _3Button = New GuiTestObject(GetMappedTestObject("_3Button"))
    End Function
    '
    ' _3: with specific test context and state.
    '		Name : button
    ' 		Text : 3
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function _3Button(anchor As TestObject, flags As Long) As  GuiTestObject
        _3Button = New GuiTestObject(GetMappedTestObject("_3Button"), anchor, flags)
    End Function
	
    '
    ' _4: with default state.
    '		Name : button
    ' 		Text : 4
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function _4Button() As GuiTestObject
        _4Button = New GuiTestObject(GetMappedTestObject("_4Button"))
    End Function
    '
    ' _4: with specific test context and state.
    '		Name : button
    ' 		Text : 4
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function _4Button(anchor As TestObject, flags As Long) As  GuiTestObject
        _4Button = New GuiTestObject(GetMappedTestObject("_4Button"), anchor, flags)
    End Function
	
    '
    ' _5: with default state.
    '		Name : button
    ' 		Text : 5
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function _5Button() As GuiTestObject
        _5Button = New GuiTestObject(GetMappedTestObject("_5Button"))
    End Function
    '
    ' _5: with specific test context and state.
    '		Name : button
    ' 		Text : 5
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function _5Button(anchor As TestObject, flags As Long) As  GuiTestObject
        _5Button = New GuiTestObject(GetMappedTestObject("_5Button"), anchor, flags)
    End Function
	
    '
    ' _6: with default state.
    '		Name : button
    ' 		Text : 6
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function _6Button() As GuiTestObject
        _6Button = New GuiTestObject(GetMappedTestObject("_6Button"))
    End Function
    '
    ' _6: with specific test context and state.
    '		Name : button
    ' 		Text : 6
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function _6Button(anchor As TestObject, flags As Long) As  GuiTestObject
        _6Button = New GuiTestObject(GetMappedTestObject("_6Button"), anchor, flags)
    End Function
	
    '
    ' _8: with default state.
    '		Name : button
    ' 		Text : 8
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function _8Button() As GuiTestObject
        _8Button = New GuiTestObject(GetMappedTestObject("_8Button"))
    End Function
    '
    ' _8: with specific test context and state.
    '		Name : button
    ' 		Text : 8
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function _8Button(anchor As TestObject, flags As Long) As  GuiTestObject
        _8Button = New GuiTestObject(GetMappedTestObject("_8Button"), anchor, flags)
    End Function
	
    '
    ' _9: with default state.
    '		Name : button
    ' 		Text : 9
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function _9Button() As GuiTestObject
        _9Button = New GuiTestObject(GetMappedTestObject("_9Button"))
    End Function
    '
    ' _9: with specific test context and state.
    '		Name : button
    ' 		Text : 9
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function _9Button(anchor As TestObject, flags As Long) As  GuiTestObject
        _9Button = New GuiTestObject(GetMappedTestObject("_9Button"), anchor, flags)
    End Function
	
    '
    ' _: with default state.
    '		Name : button
    ' 		Text :  ・
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function _Button() As GuiTestObject
        _Button = New GuiTestObject(GetMappedTestObject("_Button"))
    End Function
    '
    ' _: with specific test context and state.
    '		Name : button
    ' 		Text :  ・
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function _Button(anchor As TestObject, flags As Long) As  GuiTestObject
        _Button = New GuiTestObject(GetMappedTestObject("_Button"), anchor, flags)
    End Function
	
    '
    ' Locate and return the verification point listBox_list_1 object in the SUT.
    '
    Protected Function listBox_list_1VP() As IFtVerificationPoint
        listBox_list_1VP = vp("listBox_list_1")
    End Function
    Protected Function listBox_list_1VP(anchor As TestObject)As IFtVerificationPoint
        listBox_list_1VP = vp("listBox_list_1", anchor)
    End Function
	
    '
    ' Locate and return the verification point listBox_list_10 object in the SUT.
    '
    Protected Function listBox_list_10VP() As IFtVerificationPoint
        listBox_list_10VP = vp("listBox_list_10")
    End Function
    Protected Function listBox_list_10VP(anchor As TestObject)As IFtVerificationPoint
        listBox_list_10VP = vp("listBox_list_10", anchor)
    End Function
	
    '
    ' Locate and return the verification point listBox_list_11 object in the SUT.
    '
    Protected Function listBox_list_11VP() As IFtVerificationPoint
        listBox_list_11VP = vp("listBox_list_11")
    End Function
    Protected Function listBox_list_11VP(anchor As TestObject)As IFtVerificationPoint
        listBox_list_11VP = vp("listBox_list_11", anchor)
    End Function
	
    '
    ' Locate and return the verification point listBox_list_2 object in the SUT.
    '
    Protected Function listBox_list_2VP() As IFtVerificationPoint
        listBox_list_2VP = vp("listBox_list_2")
    End Function
    Protected Function listBox_list_2VP(anchor As TestObject)As IFtVerificationPoint
        listBox_list_2VP = vp("listBox_list_2", anchor)
    End Function
	
    '
    ' Locate and return the verification point listBox_list_3 object in the SUT.
    '
    Protected Function listBox_list_3VP() As IFtVerificationPoint
        listBox_list_3VP = vp("listBox_list_3")
    End Function
    Protected Function listBox_list_3VP(anchor As TestObject)As IFtVerificationPoint
        listBox_list_3VP = vp("listBox_list_3", anchor)
    End Function
	
    '
    ' Locate and return the verification point listBox_list_4 object in the SUT.
    '
    Protected Function listBox_list_4VP() As IFtVerificationPoint
        listBox_list_4VP = vp("listBox_list_4")
    End Function
    Protected Function listBox_list_4VP(anchor As TestObject)As IFtVerificationPoint
        listBox_list_4VP = vp("listBox_list_4", anchor)
    End Function
	
    '
    ' Locate and return the verification point listBox_list_5 object in the SUT.
    '
    Protected Function listBox_list_5VP() As IFtVerificationPoint
        listBox_list_5VP = vp("listBox_list_5")
    End Function
    Protected Function listBox_list_5VP(anchor As TestObject)As IFtVerificationPoint
        listBox_list_5VP = vp("listBox_list_5", anchor)
    End Function
	
    '
    ' Locate and return the verification point listBox_list_6 object in the SUT.
    '
    Protected Function listBox_list_6VP() As IFtVerificationPoint
        listBox_list_6VP = vp("listBox_list_6")
    End Function
    Protected Function listBox_list_6VP(anchor As TestObject)As IFtVerificationPoint
        listBox_list_6VP = vp("listBox_list_6", anchor)
    End Function
	
    '
    ' Locate and return the verification point listBox_list_7 object in the SUT.
    '
    Protected Function listBox_list_7VP() As IFtVerificationPoint
        listBox_list_7VP = vp("listBox_list_7")
    End Function
    Protected Function listBox_list_7VP(anchor As TestObject)As IFtVerificationPoint
        listBox_list_7VP = vp("listBox_list_7", anchor)
    End Function
	
    '
    ' Locate and return the verification point listBox_list_8 object in the SUT.
    '
    Protected Function listBox_list_8VP() As IFtVerificationPoint
        listBox_list_8VP = vp("listBox_list_8")
    End Function
    Protected Function listBox_list_8VP(anchor As TestObject)As IFtVerificationPoint
        listBox_list_8VP = vp("listBox_list_8", anchor)
    End Function
	
    '
    ' Locate and return the verification point listBox_list_9 object in the SUT.
    '
    Protected Function listBox_list_9VP() As IFtVerificationPoint
        listBox_list_9VP = vp("listBox_list_9")
    End Function
    Protected Function listBox_list_9VP(anchor As TestObject)As IFtVerificationPoint
        listBox_list_9VP = vp("listBox_list_9", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_1 object in the SUT.
    '
    Protected Function numericTextBox_standard_1VP() As IFtVerificationPoint
        numericTextBox_standard_1VP = vp("numericTextBox_standard_1")
    End Function
    Protected Function numericTextBox_standard_1VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_1VP = vp("numericTextBox_standard_1", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_10 object in the SUT.
    '
    Protected Function numericTextBox_standard_10VP() As IFtVerificationPoint
        numericTextBox_standard_10VP = vp("numericTextBox_standard_10")
    End Function
    Protected Function numericTextBox_standard_10VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_10VP = vp("numericTextBox_standard_10", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_11 object in the SUT.
    '
    Protected Function numericTextBox_standard_11VP() As IFtVerificationPoint
        numericTextBox_standard_11VP = vp("numericTextBox_standard_11")
    End Function
    Protected Function numericTextBox_standard_11VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_11VP = vp("numericTextBox_standard_11", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_12 object in the SUT.
    '
    Protected Function numericTextBox_standard_12VP() As IFtVerificationPoint
        numericTextBox_standard_12VP = vp("numericTextBox_standard_12")
    End Function
    Protected Function numericTextBox_standard_12VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_12VP = vp("numericTextBox_standard_12", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_13 object in the SUT.
    '
    Protected Function numericTextBox_standard_13VP() As IFtVerificationPoint
        numericTextBox_standard_13VP = vp("numericTextBox_standard_13")
    End Function
    Protected Function numericTextBox_standard_13VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_13VP = vp("numericTextBox_standard_13", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_14 object in the SUT.
    '
    Protected Function numericTextBox_standard_14VP() As IFtVerificationPoint
        numericTextBox_standard_14VP = vp("numericTextBox_standard_14")
    End Function
    Protected Function numericTextBox_standard_14VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_14VP = vp("numericTextBox_standard_14", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_2 object in the SUT.
    '
    Protected Function numericTextBox_standard_2VP() As IFtVerificationPoint
        numericTextBox_standard_2VP = vp("numericTextBox_standard_2")
    End Function
    Protected Function numericTextBox_standard_2VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_2VP = vp("numericTextBox_standard_2", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_3 object in the SUT.
    '
    Protected Function numericTextBox_standard_3VP() As IFtVerificationPoint
        numericTextBox_standard_3VP = vp("numericTextBox_standard_3")
    End Function
    Protected Function numericTextBox_standard_3VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_3VP = vp("numericTextBox_standard_3", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_4 object in the SUT.
    '
    Protected Function numericTextBox_standard_4VP() As IFtVerificationPoint
        numericTextBox_standard_4VP = vp("numericTextBox_standard_4")
    End Function
    Protected Function numericTextBox_standard_4VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_4VP = vp("numericTextBox_standard_4", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_5 object in the SUT.
    '
    Protected Function numericTextBox_standard_5VP() As IFtVerificationPoint
        numericTextBox_standard_5VP = vp("numericTextBox_standard_5")
    End Function
    Protected Function numericTextBox_standard_5VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_5VP = vp("numericTextBox_standard_5", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_6 object in the SUT.
    '
    Protected Function numericTextBox_standard_6VP() As IFtVerificationPoint
        numericTextBox_standard_6VP = vp("numericTextBox_standard_6")
    End Function
    Protected Function numericTextBox_standard_6VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_6VP = vp("numericTextBox_standard_6", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_7 object in the SUT.
    '
    Protected Function numericTextBox_standard_7VP() As IFtVerificationPoint
        numericTextBox_standard_7VP = vp("numericTextBox_standard_7")
    End Function
    Protected Function numericTextBox_standard_7VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_7VP = vp("numericTextBox_standard_7", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_8 object in the SUT.
    '
    Protected Function numericTextBox_standard_8VP() As IFtVerificationPoint
        numericTextBox_standard_8VP = vp("numericTextBox_standard_8")
    End Function
    Protected Function numericTextBox_standard_8VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_8VP = vp("numericTextBox_standard_8", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_9 object in the SUT.
    '
    Protected Function numericTextBox_standard_9VP() As IFtVerificationPoint
        numericTextBox_standard_9VP = vp("numericTextBox_standard_9")
    End Function
    Protected Function numericTextBox_standard_9VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_9VP = vp("numericTextBox_standard_9", anchor)
    End Function
	
    

    Protected Sub New()
        Dim ISI As Rational.Test.Ft.Script.Impl.IScriptInternal = Me
        ISI.SetScriptName("HP97p48p53")
    End Sub
End Class
	

#End Region

