#Region " DO NOT EDIT: This file is automatically generated "

'Only the associated template file should be edited directly.
'Helper class files are automatically regenerated from the template
'files at various times, including record actions and test object
'insertion actions.  Any changes made directly to a helper class
'file will be lost when automatically updated.

Imports Rational.Test.Ft.Object.Interfaces
Imports Rational.Test.Ft.Script
Imports Rational.Test.Ft.Vp



'Script Name   : HP97p66p72
'Generated     : 2007/11/10 6:47:24 PM
'Description   : Helper class for script
'Original Host : Windows XP x86 5.1 build 2600 Service Pack 2
 
'since  November 10, 2007
'author phl
 
Public MustInherit Class HP97p66p72Helper 
    Inherits RationalTestScript
    
    '
    ' B: with default state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : B
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function BButton() As GuiTestObject
        BButton = New GuiTestObject(GetMappedTestObject("BButton"))
    End Function
    '
    ' B: with specific test context and state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : B
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function BButton(anchor As TestObject, flags As Long) As  GuiTestObject
        BButton = New GuiTestObject(GetMappedTestObject("BButton"), anchor, flags)
    End Function
	
    '
    ' button: with default state.
    '		Name : button
    ' 		Text : 
    ' 		TabIndex : 5
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function ButtonButton() As GuiTestObject
        ButtonButton = New GuiTestObject(GetMappedTestObject("ButtonButton"))
    End Function
    '
    ' button: with specific test context and state.
    '		Name : button
    ' 		Text : 
    ' 		TabIndex : 5
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function ButtonButton(anchor As TestObject, flags As Long) As  GuiTestObject
        ButtonButton = New GuiTestObject(GetMappedTestObject("ButtonButton"), anchor, flags)
    End Function
	
    '
    ' CLX: with default state.
    '		Name : button
    ' 		Text : CL x
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function CLXButton() As GuiTestObject
        CLXButton = New GuiTestObject(GetMappedTestObject("CLXButton"))
    End Function
    '
    ' CLX: with specific test context and state.
    '		Name : button
    ' 		Text : CL x
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function CLXButton(anchor As TestObject, flags As Long) As  GuiTestObject
        CLXButton = New GuiTestObject(GetMappedTestObject("CLXButton"), anchor, flags)
    End Function
	
    '
    ' EEX: with default state.
    '		Name : button
    ' 		Text : EEX
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function EEXButton() As GuiTestObject
        EEXButton = New GuiTestObject(GetMappedTestObject("EEXButton"))
    End Function
    '
    ' EEX: with specific test context and state.
    '		Name : button
    ' 		Text : EEX
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function EEXButton(anchor As TestObject, flags As Long) As  GuiTestObject
        EEXButton = New GuiTestObject(GetMappedTestObject("EEXButton"), anchor, flags)
    End Function
	
    '
    ' ENG: with default state.
    '		Name : button
    ' 		Text : ENG
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function ENGButton() As GuiTestObject
        ENGButton = New GuiTestObject(GetMappedTestObject("ENGButton"))
    End Function
    '
    ' ENG: with specific test context and state.
    '		Name : button
    ' 		Text : ENG
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function ENGButton(anchor As TestObject, flags As Long) As  GuiTestObject
        ENGButton = New GuiTestObject(GetMappedTestObject("ENGButton"), anchor, flags)
    End Function
	
    '
    ' f: with default state.
    '		Name : button
    ' 		Text : f
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function FButton() As GuiTestObject
        FButton = New GuiTestObject(GetMappedTestObject("FButton"))
    End Function
    '
    ' f: with specific test context and state.
    '		Name : button
    ' 		Text : f
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function FButton(anchor As TestObject, flags As Long) As  GuiTestObject
        FButton = New GuiTestObject(GetMappedTestObject("FButton"), anchor, flags)
    End Function
	
    '
    ' HP97: with default state.
    '		Name : HP97
    ' 		Text : HP97
    ' 		TabIndex : 0
    ' 		.class : Mockingbird.HP.HP97.HP97
    ' 		.processName : Mockingbird.HP.HP97.exe
    '
    Protected Function HP97Window() As TopLevelSubitemTestObject
        HP97Window = New TopLevelSubitemTestObject(GetMappedTestObject("HP97Window"))
    End Function
    '
    ' HP97: with specific test context and state.
    '		Name : HP97
    ' 		Text : HP97
    ' 		TabIndex : 0
    ' 		.class : Mockingbird.HP.HP97.HP97
    ' 		.processName : Mockingbird.HP.HP97.exe
    '
    Protected Function HP97Window(anchor As TestObject, flags As Long) As  TopLevelSubitemTestObject
        HP97Window = New TopLevelSubitemTestObject(GetMappedTestObject("HP97Window"), anchor, flags)
    End Function
	
    '
    ' I: with default state.
    '		Name : button
    ' 		Text : I
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function IButton() As GuiTestObject
        IButton = New GuiTestObject(GetMappedTestObject("IButton"))
    End Function
    '
    ' I: with specific test context and state.
    '		Name : button
    ' 		Text : I
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function IButton(anchor As TestObject, flags As Long) As  GuiTestObject
        IButton = New GuiTestObject(GetMappedTestObject("IButton"), anchor, flags)
    End Function
	
    '
    ' listBox: with default state.
    '		Name : listBox
    ' 		TabIndex : 0
    ' 		.class : System.Windows.Forms.ListBox
    ' 		.classIndex : 0
    '
    Protected Function ListBoxList() As SelectGuiSubitemTestObject
        ListBoxList = New SelectGuiSubitemTestObject(GetMappedTestObject("ListBoxList"))
    End Function
    '
    ' listBox: with specific test context and state.
    '		Name : listBox
    ' 		TabIndex : 0
    ' 		.class : System.Windows.Forms.ListBox
    ' 		.classIndex : 0
    '
    Protected Function ListBoxList(anchor As TestObject, flags As Long) As  SelectGuiSubitemTestObject
        ListBoxList = New SelectGuiSubitemTestObject(GetMappedTestObject("ListBoxList"), anchor, flags)
    End Function
	
    '
    ' numericTextBox: with default state.
    '		Name : numericTextBox
    ' 		TabIndex : 0
    ' 		.class : System.Windows.Forms.TextBox
    ' 		.classIndex : 0
    '
    Protected Function NumericTextBoxText() As TextGuiSubitemTestObject
        NumericTextBoxText = New TextGuiSubitemTestObject(GetMappedTestObject("NumericTextBoxText"))
    End Function
    '
    ' numericTextBox: with specific test context and state.
    '		Name : numericTextBox
    ' 		TabIndex : 0
    ' 		.class : System.Windows.Forms.TextBox
    ' 		.classIndex : 0
    '
    Protected Function NumericTextBoxText(anchor As TestObject, flags As Long) As  TextGuiSubitemTestObject
        NumericTextBoxText = New TextGuiSubitemTestObject(GetMappedTestObject("NumericTextBoxText"), anchor, flags)
    End Function
	
    '
    ' printerFeedButton: with default state.
    '		Name : printerFeedButton
    ' 		Text : 
    ' 		TabIndex : 5
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function PrinterFeedButtonButton() As GuiTestObject
        PrinterFeedButtonButton = New GuiTestObject(GetMappedTestObject("PrinterFeedButtonButton"))
    End Function
    '
    ' printerFeedButton: with specific test context and state.
    '		Name : printerFeedButton
    ' 		Text : 
    ' 		TabIndex : 5
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function PrinterFeedButtonButton(anchor As TestObject, flags As Long) As  GuiTestObject
        PrinterFeedButtonButton = New GuiTestObject(GetMappedTestObject("PrinterFeedButtonButton"), anchor, flags)
    End Function
	
    '
    ' RCL: with default state.
    '		Name : button
    ' 		Text : RCL
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function RCLButton() As GuiTestObject
        RCLButton = New GuiTestObject(GetMappedTestObject("RCLButton"))
    End Function
    '
    ' RCL: with specific test context and state.
    '		Name : button
    ' 		Text : RCL
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function RCLButton(anchor As TestObject, flags As Long) As  GuiTestObject
        RCLButton = New GuiTestObject(GetMappedTestObject("RCLButton"), anchor, flags)
    End Function
	
    '
    ' STO: with default state.
    '		Name : button
    ' 		Text : STO
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function STOButton() As GuiTestObject
        STOButton = New GuiTestObject(GetMappedTestObject("STOButton"))
    End Function
    '
    ' STO: with specific test context and state.
    '		Name : button
    ' 		Text : STO
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function STOButton(anchor As TestObject, flags As Long) As  GuiTestObject
        STOButton = New GuiTestObject(GetMappedTestObject("STOButton"), anchor, flags)
    End Function
	
    '
    ' x: with default state.
    '		Name : button
    ' 		Text : x²
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function XButton() As GuiTestObject
        XButton = New GuiTestObject(GetMappedTestObject("XButton"))
    End Function
    '
    ' x: with specific test context and state.
    '		Name : button
    ' 		Text : x²
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function XButton(anchor As TestObject, flags As Long) As  GuiTestObject
        XButton = New GuiTestObject(GetMappedTestObject("XButton"), anchor, flags)
    End Function
	
    '
    ' _0: with default state.
    '		Name : button
    ' 		Text : 0
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function _0Button() As GuiTestObject
        _0Button = New GuiTestObject(GetMappedTestObject("_0Button"))
    End Function
    '
    ' _0: with specific test context and state.
    '		Name : button
    ' 		Text : 0
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function _0Button(anchor As TestObject, flags As Long) As  GuiTestObject
        _0Button = New GuiTestObject(GetMappedTestObject("_0Button"), anchor, flags)
    End Function
	
    '
    ' _1: with default state.
    '		Name : button
    ' 		Text : 1
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function _1Button() As GuiTestObject
        _1Button = New GuiTestObject(GetMappedTestObject("_1Button"))
    End Function
    '
    ' _1: with specific test context and state.
    '		Name : button
    ' 		Text : 1
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function _1Button(anchor As TestObject, flags As Long) As  GuiTestObject
        _1Button = New GuiTestObject(GetMappedTestObject("_1Button"), anchor, flags)
    End Function
	
    '
    ' _2: with default state.
    '		Name : button
    ' 		Text : 2
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function _2Button() As GuiTestObject
        _2Button = New GuiTestObject(GetMappedTestObject("_2Button"))
    End Function
    '
    ' _2: with specific test context and state.
    '		Name : button
    ' 		Text : 2
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function _2Button(anchor As TestObject, flags As Long) As  GuiTestObject
        _2Button = New GuiTestObject(GetMappedTestObject("_2Button"), anchor, flags)
    End Function
	
    '
    ' _3: with default state.
    '		Name : button
    ' 		Text : 3
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function _3Button() As GuiTestObject
        _3Button = New GuiTestObject(GetMappedTestObject("_3Button"))
    End Function
    '
    ' _3: with specific test context and state.
    '		Name : button
    ' 		Text : 3
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function _3Button(anchor As TestObject, flags As Long) As  GuiTestObject
        _3Button = New GuiTestObject(GetMappedTestObject("_3Button"), anchor, flags)
    End Function
	
    '
    ' _4: with default state.
    '		Name : button
    ' 		Text : 4
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function _4Button() As GuiTestObject
        _4Button = New GuiTestObject(GetMappedTestObject("_4Button"))
    End Function
    '
    ' _4: with specific test context and state.
    '		Name : button
    ' 		Text : 4
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function _4Button(anchor As TestObject, flags As Long) As  GuiTestObject
        _4Button = New GuiTestObject(GetMappedTestObject("_4Button"), anchor, flags)
    End Function
	
    '
    ' _5: with default state.
    '		Name : button
    ' 		Text : 5
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function _5Button() As GuiTestObject
        _5Button = New GuiTestObject(GetMappedTestObject("_5Button"))
    End Function
    '
    ' _5: with specific test context and state.
    '		Name : button
    ' 		Text : 5
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function _5Button(anchor As TestObject, flags As Long) As  GuiTestObject
        _5Button = New GuiTestObject(GetMappedTestObject("_5Button"), anchor, flags)
    End Function
	
    '
    ' _6: with default state.
    '		Name : button
    ' 		Text : 6
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function _6Button() As GuiTestObject
        _6Button = New GuiTestObject(GetMappedTestObject("_6Button"))
    End Function
    '
    ' _6: with specific test context and state.
    '		Name : button
    ' 		Text : 6
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function _6Button(anchor As TestObject, flags As Long) As  GuiTestObject
        _6Button = New GuiTestObject(GetMappedTestObject("_6Button"), anchor, flags)
    End Function
	
    '
    ' _7: with default state.
    '		Name : button
    ' 		Text : 7
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function _7Button() As GuiTestObject
        _7Button = New GuiTestObject(GetMappedTestObject("_7Button"))
    End Function
    '
    ' _7: with specific test context and state.
    '		Name : button
    ' 		Text : 7
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function _7Button(anchor As TestObject, flags As Long) As  GuiTestObject
        _7Button = New GuiTestObject(GetMappedTestObject("_7Button"), anchor, flags)
    End Function
	
    '
    ' _9: with default state.
    '		Name : button
    ' 		Text : 9
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function _9Button() As GuiTestObject
        _9Button = New GuiTestObject(GetMappedTestObject("_9Button"))
    End Function
    '
    ' _9: with specific test context and state.
    '		Name : button
    ' 		Text : 9
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function _9Button(anchor As TestObject, flags As Long) As  GuiTestObject
        _9Button = New GuiTestObject(GetMappedTestObject("_9Button"), anchor, flags)
    End Function
	
    '
    ' _: with default state.
    '		Name : button
    ' 		Text : ×
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function _Button() As GuiTestObject
        _Button = New GuiTestObject(GetMappedTestObject("_Button"))
    End Function
    '
    ' _: with specific test context and state.
    '		Name : button
    ' 		Text : ×
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function _Button(anchor As TestObject, flags As Long) As  GuiTestObject
        _Button = New GuiTestObject(GetMappedTestObject("_Button"), anchor, flags)
    End Function
	
    '
    ' _: with default state.
    '		Name : button
    ' 		Text :  ・
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function _Button2() As GuiTestObject
        _Button2 = New GuiTestObject(GetMappedTestObject("_Button2"))
    End Function
    '
    ' _: with specific test context and state.
    '		Name : button
    ' 		Text :  ・
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function _Button2(anchor As TestObject, flags As Long) As  GuiTestObject
        _Button2 = New GuiTestObject(GetMappedTestObject("_Button2"), anchor, flags)
    End Function
	
    '
    ' Locate and return the verification point listBox_list_1 object in the SUT.
    '
    Protected Function listBox_list_1VP() As IFtVerificationPoint
        listBox_list_1VP = vp("listBox_list_1")
    End Function
    Protected Function listBox_list_1VP(anchor As TestObject)As IFtVerificationPoint
        listBox_list_1VP = vp("listBox_list_1", anchor)
    End Function
	
    '
    ' Locate and return the verification point listBox_list_2 object in the SUT.
    '
    Protected Function listBox_list_2VP() As IFtVerificationPoint
        listBox_list_2VP = vp("listBox_list_2")
    End Function
    Protected Function listBox_list_2VP(anchor As TestObject)As IFtVerificationPoint
        listBox_list_2VP = vp("listBox_list_2", anchor)
    End Function
	
    '
    ' Locate and return the verification point listBox_list_3 object in the SUT.
    '
    Protected Function listBox_list_3VP() As IFtVerificationPoint
        listBox_list_3VP = vp("listBox_list_3")
    End Function
    Protected Function listBox_list_3VP(anchor As TestObject)As IFtVerificationPoint
        listBox_list_3VP = vp("listBox_list_3", anchor)
    End Function
	
    '
    ' Locate and return the verification point listBox_list_4 object in the SUT.
    '
    Protected Function listBox_list_4VP() As IFtVerificationPoint
        listBox_list_4VP = vp("listBox_list_4")
    End Function
    Protected Function listBox_list_4VP(anchor As TestObject)As IFtVerificationPoint
        listBox_list_4VP = vp("listBox_list_4", anchor)
    End Function
	
    '
    ' Locate and return the verification point listBox_list_5 object in the SUT.
    '
    Protected Function listBox_list_5VP() As IFtVerificationPoint
        listBox_list_5VP = vp("listBox_list_5")
    End Function
    Protected Function listBox_list_5VP(anchor As TestObject)As IFtVerificationPoint
        listBox_list_5VP = vp("listBox_list_5", anchor)
    End Function
	
    '
    ' Locate and return the verification point listBox_list_6 object in the SUT.
    '
    Protected Function listBox_list_6VP() As IFtVerificationPoint
        listBox_list_6VP = vp("listBox_list_6")
    End Function
    Protected Function listBox_list_6VP(anchor As TestObject)As IFtVerificationPoint
        listBox_list_6VP = vp("listBox_list_6", anchor)
    End Function
	
    '
    ' Locate and return the verification point listBox_list_7 object in the SUT.
    '
    Protected Function listBox_list_7VP() As IFtVerificationPoint
        listBox_list_7VP = vp("listBox_list_7")
    End Function
    Protected Function listBox_list_7VP(anchor As TestObject)As IFtVerificationPoint
        listBox_list_7VP = vp("listBox_list_7", anchor)
    End Function
	
    '
    ' Locate and return the verification point listBox_list_8 object in the SUT.
    '
    Protected Function listBox_list_8VP() As IFtVerificationPoint
        listBox_list_8VP = vp("listBox_list_8")
    End Function
    Protected Function listBox_list_8VP(anchor As TestObject)As IFtVerificationPoint
        listBox_list_8VP = vp("listBox_list_8", anchor)
    End Function
	
    '
    ' Locate and return the verification point listBox_list_9 object in the SUT.
    '
    Protected Function listBox_list_9VP() As IFtVerificationPoint
        listBox_list_9VP = vp("listBox_list_9")
    End Function
    Protected Function listBox_list_9VP(anchor As TestObject)As IFtVerificationPoint
        listBox_list_9VP = vp("listBox_list_9", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_1 object in the SUT.
    '
    Protected Function numericTextBox_standard_1VP() As IFtVerificationPoint
        numericTextBox_standard_1VP = vp("numericTextBox_standard_1")
    End Function
    Protected Function numericTextBox_standard_1VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_1VP = vp("numericTextBox_standard_1", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_10 object in the SUT.
    '
    Protected Function numericTextBox_standard_10VP() As IFtVerificationPoint
        numericTextBox_standard_10VP = vp("numericTextBox_standard_10")
    End Function
    Protected Function numericTextBox_standard_10VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_10VP = vp("numericTextBox_standard_10", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_11 object in the SUT.
    '
    Protected Function numericTextBox_standard_11VP() As IFtVerificationPoint
        numericTextBox_standard_11VP = vp("numericTextBox_standard_11")
    End Function
    Protected Function numericTextBox_standard_11VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_11VP = vp("numericTextBox_standard_11", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_12 object in the SUT.
    '
    Protected Function numericTextBox_standard_12VP() As IFtVerificationPoint
        numericTextBox_standard_12VP = vp("numericTextBox_standard_12")
    End Function
    Protected Function numericTextBox_standard_12VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_12VP = vp("numericTextBox_standard_12", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_13 object in the SUT.
    '
    Protected Function numericTextBox_standard_13VP() As IFtVerificationPoint
        numericTextBox_standard_13VP = vp("numericTextBox_standard_13")
    End Function
    Protected Function numericTextBox_standard_13VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_13VP = vp("numericTextBox_standard_13", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_14 object in the SUT.
    '
    Protected Function numericTextBox_standard_14VP() As IFtVerificationPoint
        numericTextBox_standard_14VP = vp("numericTextBox_standard_14")
    End Function
    Protected Function numericTextBox_standard_14VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_14VP = vp("numericTextBox_standard_14", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_15 object in the SUT.
    '
    Protected Function numericTextBox_standard_15VP() As IFtVerificationPoint
        numericTextBox_standard_15VP = vp("numericTextBox_standard_15")
    End Function
    Protected Function numericTextBox_standard_15VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_15VP = vp("numericTextBox_standard_15", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_16 object in the SUT.
    '
    Protected Function numericTextBox_standard_16VP() As IFtVerificationPoint
        numericTextBox_standard_16VP = vp("numericTextBox_standard_16")
    End Function
    Protected Function numericTextBox_standard_16VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_16VP = vp("numericTextBox_standard_16", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_17 object in the SUT.
    '
    Protected Function numericTextBox_standard_17VP() As IFtVerificationPoint
        numericTextBox_standard_17VP = vp("numericTextBox_standard_17")
    End Function
    Protected Function numericTextBox_standard_17VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_17VP = vp("numericTextBox_standard_17", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_18 object in the SUT.
    '
    Protected Function numericTextBox_standard_18VP() As IFtVerificationPoint
        numericTextBox_standard_18VP = vp("numericTextBox_standard_18")
    End Function
    Protected Function numericTextBox_standard_18VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_18VP = vp("numericTextBox_standard_18", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_19 object in the SUT.
    '
    Protected Function numericTextBox_standard_19VP() As IFtVerificationPoint
        numericTextBox_standard_19VP = vp("numericTextBox_standard_19")
    End Function
    Protected Function numericTextBox_standard_19VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_19VP = vp("numericTextBox_standard_19", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_2 object in the SUT.
    '
    Protected Function numericTextBox_standard_2VP() As IFtVerificationPoint
        numericTextBox_standard_2VP = vp("numericTextBox_standard_2")
    End Function
    Protected Function numericTextBox_standard_2VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_2VP = vp("numericTextBox_standard_2", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_20 object in the SUT.
    '
    Protected Function numericTextBox_standard_20VP() As IFtVerificationPoint
        numericTextBox_standard_20VP = vp("numericTextBox_standard_20")
    End Function
    Protected Function numericTextBox_standard_20VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_20VP = vp("numericTextBox_standard_20", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_21 object in the SUT.
    '
    Protected Function numericTextBox_standard_21VP() As IFtVerificationPoint
        numericTextBox_standard_21VP = vp("numericTextBox_standard_21")
    End Function
    Protected Function numericTextBox_standard_21VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_21VP = vp("numericTextBox_standard_21", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_22 object in the SUT.
    '
    Protected Function numericTextBox_standard_22VP() As IFtVerificationPoint
        numericTextBox_standard_22VP = vp("numericTextBox_standard_22")
    End Function
    Protected Function numericTextBox_standard_22VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_22VP = vp("numericTextBox_standard_22", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_23 object in the SUT.
    '
    Protected Function numericTextBox_standard_23VP() As IFtVerificationPoint
        numericTextBox_standard_23VP = vp("numericTextBox_standard_23")
    End Function
    Protected Function numericTextBox_standard_23VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_23VP = vp("numericTextBox_standard_23", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_3 object in the SUT.
    '
    Protected Function numericTextBox_standard_3VP() As IFtVerificationPoint
        numericTextBox_standard_3VP = vp("numericTextBox_standard_3")
    End Function
    Protected Function numericTextBox_standard_3VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_3VP = vp("numericTextBox_standard_3", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_4 object in the SUT.
    '
    Protected Function numericTextBox_standard_4VP() As IFtVerificationPoint
        numericTextBox_standard_4VP = vp("numericTextBox_standard_4")
    End Function
    Protected Function numericTextBox_standard_4VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_4VP = vp("numericTextBox_standard_4", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_5 object in the SUT.
    '
    Protected Function numericTextBox_standard_5VP() As IFtVerificationPoint
        numericTextBox_standard_5VP = vp("numericTextBox_standard_5")
    End Function
    Protected Function numericTextBox_standard_5VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_5VP = vp("numericTextBox_standard_5", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_6 object in the SUT.
    '
    Protected Function numericTextBox_standard_6VP() As IFtVerificationPoint
        numericTextBox_standard_6VP = vp("numericTextBox_standard_6")
    End Function
    Protected Function numericTextBox_standard_6VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_6VP = vp("numericTextBox_standard_6", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_7 object in the SUT.
    '
    Protected Function numericTextBox_standard_7VP() As IFtVerificationPoint
        numericTextBox_standard_7VP = vp("numericTextBox_standard_7")
    End Function
    Protected Function numericTextBox_standard_7VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_7VP = vp("numericTextBox_standard_7", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_8 object in the SUT.
    '
    Protected Function numericTextBox_standard_8VP() As IFtVerificationPoint
        numericTextBox_standard_8VP = vp("numericTextBox_standard_8")
    End Function
    Protected Function numericTextBox_standard_8VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_8VP = vp("numericTextBox_standard_8", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_9 object in the SUT.
    '
    Protected Function numericTextBox_standard_9VP() As IFtVerificationPoint
        numericTextBox_standard_9VP = vp("numericTextBox_standard_9")
    End Function
    Protected Function numericTextBox_standard_9VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_9VP = vp("numericTextBox_standard_9", anchor)
    End Function
	
    

    Protected Sub New()
        Dim ISI As Rational.Test.Ft.Script.Impl.IScriptInternal = Me
        ISI.SetScriptName("HP97p66p72")
    End Sub
End Class
	

#End Region

