#Region " DO NOT EDIT: This file is automatically generated "

'Only the associated template file should be edited directly.
'Helper class files are automatically regenerated from the template
'files at various times, including record actions and test object
'insertion actions.  Any changes made directly to a helper class
'file will be lost when automatically updated.

Imports Rational.Test.Ft.Object.Interfaces
Imports Rational.Test.Ft.Script
Imports Rational.Test.Ft.Vp



'Script Name   : HP97p47
'Generated     : 2007/06/25 7:15:47 PM
'Description   : Helper class for script
'Original Host : Windows XP x86 5.1 build 2600 Service Pack 2
 
'since  June 25, 2007
'author phl
 
Public MustInherit Class HP97p47Helper 
    Inherits RationalTestScript
    
    '
    ' f: with default state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : f
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function FButton() As GuiTestObject
        FButton = New GuiTestObject(GetMappedTestObject("FButton"))
    End Function
    '
    ' f: with specific test context and state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : f
    ' 		.class : System.Windows.Forms.Button
    ' 		.classIndex : 0
    '
    Protected Function FButton(anchor As TestObject, flags As Long) As  GuiTestObject
        FButton = New GuiTestObject(GetMappedTestObject("FButton"), anchor, flags)
    End Function
	
    '
    ' HP97: with default state.
    '		Name : HP97
    ' 		TabIndex : 0
    ' 		Text : HP97
    ' 		.class : Mockingbird.HP.HP97.HP97
    ' 		.processName : Mockingbird.HP.HP97.exe
    '
    Protected Function HP97Window() As TopLevelSubitemTestObject
        HP97Window = New TopLevelSubitemTestObject(GetMappedTestObject("HP97Window"))
    End Function
    '
    ' HP97: with specific test context and state.
    '		Name : HP97
    ' 		TabIndex : 0
    ' 		Text : HP97
    ' 		.class : Mockingbird.HP.HP97.HP97
    ' 		.processName : Mockingbird.HP.HP97.exe
    '
    Protected Function HP97Window(anchor As TestObject, flags As Long) As  TopLevelSubitemTestObject
        HP97Window = New TopLevelSubitemTestObject(GetMappedTestObject("HP97Window"), anchor, flags)
    End Function
	
    '
    ' listBox: with default state.
    '		Name : listBox
    ' 		TabIndex : 0
    ' 		.class : System.Windows.Forms.ListBox
    ' 		.classIndex : 0
    '
    Protected Function ListBoxList() As SelectGuiSubitemTestObject
        ListBoxList = New SelectGuiSubitemTestObject(GetMappedTestObject("ListBoxList"))
    End Function
    '
    ' listBox: with specific test context and state.
    '		Name : listBox
    ' 		TabIndex : 0
    ' 		.class : System.Windows.Forms.ListBox
    ' 		.classIndex : 0
    '
    Protected Function ListBoxList(anchor As TestObject, flags As Long) As  SelectGuiSubitemTestObject
        ListBoxList = New SelectGuiSubitemTestObject(GetMappedTestObject("ListBoxList"), anchor, flags)
    End Function
	
    '
    ' menuStrip: with default state.
    '		Name : menuStrip
    ' 		TabIndex : 6
    ' 		.class : System.Windows.Forms.MenuStrip
    ' 		.classIndex : 0
    '
    Protected Function MenuStripMenuBar() As GuiSubitemTestObject
        MenuStripMenuBar = New GuiSubitemTestObject(GetMappedTestObject("MenuStripMenuBar"))
    End Function
    '
    ' menuStrip: with specific test context and state.
    '		Name : menuStrip
    ' 		TabIndex : 6
    ' 		.class : System.Windows.Forms.MenuStrip
    ' 		.classIndex : 0
    '
    Protected Function MenuStripMenuBar(anchor As TestObject, flags As Long) As  GuiSubitemTestObject
        MenuStripMenuBar = New GuiSubitemTestObject(GetMappedTestObject("MenuStripMenuBar"), anchor, flags)
    End Function
	
    '
    ' numericTextBox: with default state.
    '		Name : numericTextBox
    ' 		TabIndex : 0
    ' 		.class : System.Windows.Forms.TextBox
    ' 		.classIndex : 0
    '
    Protected Function NumericTextBoxText() As TextGuiSubitemTestObject
        NumericTextBoxText = New TextGuiSubitemTestObject(GetMappedTestObject("NumericTextBoxText"))
    End Function
    '
    ' numericTextBox: with specific test context and state.
    '		Name : numericTextBox
    ' 		TabIndex : 0
    ' 		.class : System.Windows.Forms.TextBox
    ' 		.classIndex : 0
    '
    Protected Function NumericTextBoxText(anchor As TestObject, flags As Long) As  TextGuiSubitemTestObject
        NumericTextBoxText = New TextGuiSubitemTestObject(GetMappedTestObject("NumericTextBoxText"), anchor, flags)
    End Function
	
    '
    ' PRINTX: with default state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : PRINT x
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : STACK
    ' 		.classIndex : 0
    '
    Protected Function PRINTXButton() As GuiTestObject
        PRINTXButton = New GuiTestObject(GetMappedTestObject("PRINTXButton"))
    End Function
    '
    ' PRINTX: with specific test context and state.
    '		Name : button
    ' 		TabIndex : 1
    ' 		Text : PRINT x
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : STACK
    ' 		.classIndex : 0
    '
    Protected Function PRINTXButton(anchor As TestObject, flags As Long) As  GuiTestObject
        PRINTXButton = New GuiTestObject(GetMappedTestObject("PRINTXButton"), anchor, flags)
    End Function
	
    '
    ' Locate and return the verification point listBox_list object in the SUT.
    '
    Protected Function listBox_listVP() As IFtVerificationPoint
        listBox_listVP = vp("listBox_list")
    End Function
    Protected Function listBox_listVP(anchor As TestObject)As IFtVerificationPoint
        listBox_listVP = vp("listBox_list", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard object in the SUT.
    '
    Protected Function numericTextBox_standardVP() As IFtVerificationPoint
        numericTextBox_standardVP = vp("numericTextBox_standard")
    End Function
    Protected Function numericTextBox_standardVP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standardVP = vp("numericTextBox_standard", anchor)
    End Function
	
    

    Protected Sub New()
        Dim ISI As Rational.Test.Ft.Script.Impl.IScriptInternal = Me
        ISI.SetScriptName("HP97p47")
    End Sub
End Class
	

#End Region

