#Region " DO NOT EDIT: This file is automatically generated "

'Only the associated template file should be edited directly.
'Helper class files are automatically regenerated from the template
'files at various times, including record actions and test object
'insertion actions.  Any changes made directly to a helper class
'file will be lost when automatically updated.

Imports Rational.Test.Ft.Object.Interfaces
Imports Rational.Test.Ft.Script
Imports Rational.Test.Ft.Vp



'Script Name   : HP97p45
'Generated     : 2008/03/01 3:05:54 PM
'Description   : Helper class for script
'Original Host : Windows XP x86 5.1 build 2600 Service Pack 2
 
'since  March 01, 2008
'author phl
 
Public MustInherit Class HP97p45Helper 
    Inherits RationalTestScript
    
    '
    ' alphabeticTextBox: with default state.
    '		Name : alphabeticTextBox
    ' 		TabIndex : 2
    ' 		.class : System.Windows.Forms.TextBox
    ' 		.classIndex : 0
    '
    Protected Function AlphabeticTextBoxText() As TextGuiSubitemTestObject
        AlphabeticTextBoxText = New TextGuiSubitemTestObject(GetMappedTestObject("AlphabeticTextBoxText"))
    End Function
    '
    ' alphabeticTextBox: with specific test context and state.
    '		Name : alphabeticTextBox
    ' 		TabIndex : 2
    ' 		.class : System.Windows.Forms.TextBox
    ' 		.classIndex : 0
    '
    Protected Function AlphabeticTextBoxText(anchor As TestObject, flags As Long) As  TextGuiSubitemTestObject
        AlphabeticTextBoxText = New TextGuiSubitemTestObject(GetMappedTestObject("AlphabeticTextBoxText"), anchor, flags)
    End Function
	
    '
    ' CHS: with default state.
    '		Name : button
    ' 		Text : CHS
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : RAD
    ' 		.classIndex : 0
    '
    Protected Function CHSButton() As GuiTestObject
        CHSButton = New GuiTestObject(GetMappedTestObject("CHSButton"))
    End Function
    '
    ' CHS: with specific test context and state.
    '		Name : button
    ' 		Text : CHS
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : RAD
    ' 		.classIndex : 0
    '
    Protected Function CHSButton(anchor As TestObject, flags As Long) As  GuiTestObject
        CHSButton = New GuiTestObject(GetMappedTestObject("CHSButton"), anchor, flags)
    End Function
	
    '
    ' CLX: with default state.
    '		Name : button
    ' 		Text : CL x
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : P⇄S
    ' 		.classIndex : 0
    '
    Protected Function CLXButton() As GuiTestObject
        CLXButton = New GuiTestObject(GetMappedTestObject("CLXButton"))
    End Function
    '
    ' CLX: with specific test context and state.
    '		Name : button
    ' 		Text : CL x
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : P⇄S
    ' 		.classIndex : 0
    '
    Protected Function CLXButton(anchor As TestObject, flags As Long) As  GuiTestObject
        CLXButton = New GuiTestObject(GetMappedTestObject("CLXButton"), anchor, flags)
    End Function
	
    '
    ' HP97: with default state.
    '		Name : HP97
    ' 		Text : HP97
    ' 		TabIndex : 0
    ' 		.class : Mockingbird.HP.HP97.HP97
    ' 		.processName : Mockingbird.HP.HP97.exe
    '
    Protected Function HP97Window() As TopLevelSubitemTestObject
        HP97Window = New TopLevelSubitemTestObject(GetMappedTestObject("HP97Window"))
    End Function
    '
    ' HP97: with specific test context and state.
    '		Name : HP97
    ' 		Text : HP97
    ' 		TabIndex : 0
    ' 		.class : Mockingbird.HP.HP97.HP97
    ' 		.processName : Mockingbird.HP.HP97.exe
    '
    Protected Function HP97Window(anchor As TestObject, flags As Long) As  TopLevelSubitemTestObject
        HP97Window = New TopLevelSubitemTestObject(GetMappedTestObject("HP97Window"), anchor, flags)
    End Function
	
    '
    ' listBox: with default state.
    '		Name : listBox
    ' 		TabIndex : 0
    ' 		.class : System.Windows.Forms.ListBox
    ' 		.classIndex : 0
    '
    Protected Function ListBoxList() As SelectGuiSubitemTestObject
        ListBoxList = New SelectGuiSubitemTestObject(GetMappedTestObject("ListBoxList"))
    End Function
    '
    ' listBox: with specific test context and state.
    '		Name : listBox
    ' 		TabIndex : 0
    ' 		.class : System.Windows.Forms.ListBox
    ' 		.classIndex : 0
    '
    Protected Function ListBoxList(anchor As TestObject, flags As Long) As  SelectGuiSubitemTestObject
        ListBoxList = New SelectGuiSubitemTestObject(GetMappedTestObject("ListBoxList"), anchor, flags)
    End Function
	
    '
    ' numericTextBox: with default state.
    '		Name : numericTextBox
    ' 		TabIndex : 0
    ' 		.class : System.Windows.Forms.TextBox
    ' 		.classIndex : 0
    '
    Protected Function NumericTextBoxText() As TextGuiSubitemTestObject
        NumericTextBoxText = New TextGuiSubitemTestObject(GetMappedTestObject("NumericTextBoxText"))
    End Function
    '
    ' numericTextBox: with specific test context and state.
    '		Name : numericTextBox
    ' 		TabIndex : 0
    ' 		.class : System.Windows.Forms.TextBox
    ' 		.classIndex : 0
    '
    Protected Function NumericTextBoxText(anchor As TestObject, flags As Long) As  TextGuiSubitemTestObject
        NumericTextBoxText = New TextGuiSubitemTestObject(GetMappedTestObject("NumericTextBoxText"), anchor, flags)
    End Function
	
    '
    ' Sqrt: with default state.
    '		Name : button
    ' 		Text : √x̅
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : S
    ' 		.classIndex : 0
    '
    Protected Function SqrtButton() As GuiTestObject
        SqrtButton = New GuiTestObject(GetMappedTestObject("SqrtButton"))
    End Function
    '
    ' Sqrt: with specific test context and state.
    '		Name : button
    ' 		Text : √x̅
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : S
    ' 		.classIndex : 0
    '
    Protected Function SqrtButton(anchor As TestObject, flags As Long) As  GuiTestObject
        SqrtButton = New GuiTestObject(GetMappedTestObject("SqrtButton"), anchor, flags)
    End Function
	
    '
    ' toggleManTraceNorm: with default state.
    '		Name : button
    ' 		Text : 
    ' 		TabIndex : 5
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : TRACE
    ' 		.classIndex : 0
    '
    Protected Function ToggleManTraceNormButton() As GuiTestObject
        ToggleManTraceNormButton = New GuiTestObject(GetMappedTestObject("ToggleManTraceNormButton"))
    End Function
    '
    ' toggleManTraceNorm: with specific test context and state.
    '		Name : button
    ' 		Text : 
    ' 		TabIndex : 5
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : TRACE
    ' 		.classIndex : 0
    '
    Protected Function ToggleManTraceNormButton(anchor As TestObject, flags As Long) As  GuiTestObject
        ToggleManTraceNormButton = New GuiTestObject(GetMappedTestObject("ToggleManTraceNormButton"), anchor, flags)
    End Function
	
    '
    ' _4: with default state.
    '		Name : button
    ' 		Text : 4
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : x≠0?
    ' 		.classIndex : 0
    '
    Protected Function _4Button() As GuiTestObject
        _4Button = New GuiTestObject(GetMappedTestObject("_4Button"))
    End Function
    '
    ' _4: with specific test context and state.
    '		Name : button
    ' 		Text : 4
    ' 		TabIndex : 1
    ' 		.class : System.Windows.Forms.Button
    ' 		.priorLabel : x≠0?
    ' 		.classIndex : 0
    '
    Protected Function _4Button(anchor As TestObject, flags As Long) As  GuiTestObject
        _4Button = New GuiTestObject(GetMappedTestObject("_4Button"), anchor, flags)
    End Function
	
    '
    ' Locate and return the verification point alphabeticTextBox_standard object in the SUT.
    '
    Protected Function alphabeticTextBox_standardVP() As IFtVerificationPoint
        alphabeticTextBox_standardVP = vp("alphabeticTextBox_standard")
    End Function
    Protected Function alphabeticTextBox_standardVP(anchor As TestObject)As IFtVerificationPoint
        alphabeticTextBox_standardVP = vp("alphabeticTextBox_standard", anchor)
    End Function
	
    '
    ' Locate and return the verification point alphabeticTextBox_standard_2 object in the SUT.
    '
    Protected Function alphabeticTextBox_standard_2VP() As IFtVerificationPoint
        alphabeticTextBox_standard_2VP = vp("alphabeticTextBox_standard_2")
    End Function
    Protected Function alphabeticTextBox_standard_2VP(anchor As TestObject)As IFtVerificationPoint
        alphabeticTextBox_standard_2VP = vp("alphabeticTextBox_standard_2", anchor)
    End Function
	
    '
    ' Locate and return the verification point listBox_list object in the SUT.
    '
    Protected Function listBox_listVP() As IFtVerificationPoint
        listBox_listVP = vp("listBox_list")
    End Function
    Protected Function listBox_listVP(anchor As TestObject)As IFtVerificationPoint
        listBox_listVP = vp("listBox_list", anchor)
    End Function
	
    '
    ' Locate and return the verification point listBox_list_2 object in the SUT.
    '
    Protected Function listBox_list_2VP() As IFtVerificationPoint
        listBox_list_2VP = vp("listBox_list_2")
    End Function
    Protected Function listBox_list_2VP(anchor As TestObject)As IFtVerificationPoint
        listBox_list_2VP = vp("listBox_list_2", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_1 object in the SUT.
    '
    Protected Function numericTextBox_standard_1VP() As IFtVerificationPoint
        numericTextBox_standard_1VP = vp("numericTextBox_standard_1")
    End Function
    Protected Function numericTextBox_standard_1VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_1VP = vp("numericTextBox_standard_1", anchor)
    End Function
	
    '
    ' Locate and return the verification point numericTextBox_standard_2 object in the SUT.
    '
    Protected Function numericTextBox_standard_2VP() As IFtVerificationPoint
        numericTextBox_standard_2VP = vp("numericTextBox_standard_2")
    End Function
    Protected Function numericTextBox_standard_2VP(anchor As TestObject)As IFtVerificationPoint
        numericTextBox_standard_2VP = vp("numericTextBox_standard_2", anchor)
    End Function
	
    

    Protected Sub New()
        Dim ISI As Rational.Test.Ft.Script.Impl.IScriptInternal = Me
        ISI.SetScriptName("HP97p45")
    End Sub
End Class
	

#End Region

