//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mockingbird.HP.Class_Library {
    using System;
    
    
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, formatting them, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilderEx class via the ResXFileCodeGeneratorEx custom tool.
    // To add or remove a member, edit your .ResX file then rerun the ResXFileCodeGeneratorEx custom tool or rebuild your VS.NET project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("DMKSoftware.CodeGenerators.Tools.StronglyTypedResourceBuilderEx", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public sealed class Localization {
        
        private static global::System.Resources.ResourceManager _resourceManager;
        
        private static global::System.Globalization.CultureInfo _resourceCulture;
        
        private Localization() {
        }
        
        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(_resourceManager, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mockingbird.HP.Class_Library.Localization", typeof(Localization).Assembly);
                    _resourceManager = temp;
                }
                return _resourceManager;
            }
        }
        
        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return _resourceCulture;
            }
            set {
                _resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'File {0} not found'.
        /// </summary>
        public static string CannotOpenFile {
            get {
                return ResourceManager.GetString("CannotOpenFile", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Error         '.
        /// </summary>
        public static string DisplayError {
            get {
                return ResourceManager.GetString("DisplayError", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Invalid argument in a computation'.
        /// </summary>
        public static string ErrorDescription {
            get {
                return ResourceManager.GetString("ErrorDescription", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Open Failed'.
        /// </summary>
        public static string ErrorDuringOpen {
            get {
                return ResourceManager.GetString("ErrorDuringOpen", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Save Failed'.
        /// </summary>
        public static string ErrorDuringSave {
            get {
                return ResourceManager.GetString("ErrorDuringSave", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Unable to open file {0} because {1}'.
        /// </summary>
        public static string ExceptionOpeningFile {
            get {
                return ResourceManager.GetString("ExceptionOpeningFile", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Unable to save file {0} because {1}	'.
        /// </summary>
        public static string ExceptionSavingFile {
            get {
                return ResourceManager.GetString("ExceptionSavingFile", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Incompatible version: file has version {0} but program expects version {1}.'.
        /// </summary>
        public static string FileHasVersion {
            get {
                return ResourceManager.GetString("FileHasVersion", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'File Not Found'.
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Incompatible Version'.
        /// </summary>
        public static string IncompatibleVersion {
            get {
                return ResourceManager.GetString("IncompatibleVersion", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Incorrect argument count {0}; expected to be {1} or {2}'.
        /// </summary>
        public static string IncorrectArgumentCount {
            get {
                return ResourceManager.GetString("IncorrectArgumentCount", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Incorrect command {0}; expected to be {1} or {2}'.
        /// </summary>
        public static string IncorrectCommand {
            get {
                return ResourceManager.GetString("IncorrectCommand", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Incorrect Command Line Arguments'.
        /// </summary>
        public static string IncorrectCommandLineArguments {
            get {
                return ResourceManager.GetString("IncorrectCommandLineArguments", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Execution interrupted by user'.
        /// </summary>
        public static string InterruptDescription {
            get {
                return ResourceManager.GetString("InterruptDescription", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'ERROR'.
        /// </summary>
        public static string PrinterError {
            get {
                return ResourceManager.GetString("PrinterError", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Application shutdown'.
        /// </summary>
        public static string ShutdownDescription {
            get {
                return ResourceManager.GetString("ShutdownDescription", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Program completed normally'.
        /// </summary>
        public static string StopDescription {
            get {
                return ResourceManager.GetString("StopDescription", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Syntax error on token {0}'.
        /// </summary>
        public static string SyntaxErrorDescription {
            get {
                return ResourceManager.GetString("SyntaxErrorDescription", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Untitled'.
        /// </summary>
        public static string UntitledFileName {
            get {
                return ResourceManager.GetString("UntitledFileName", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Formats a localized string similar to 'File {0} not found'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string CannotOpenFileFormat(object arg0) {
            return string.Format(_resourceCulture, CannotOpenFile, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Unable to open file {0} because {1}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <param name="arg1">An object (1) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string ExceptionOpeningFileFormat(object arg0, object arg1) {
            return string.Format(_resourceCulture, ExceptionOpeningFile, arg0, arg1);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Unable to save file {0} because {1}	'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <param name="arg1">An object (1) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string ExceptionSavingFileFormat(object arg0, object arg1) {
            return string.Format(_resourceCulture, ExceptionSavingFile, arg0, arg1);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Incompatible version: file has version {0} but program expects version {1}.'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <param name="arg1">An object (1) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string FileHasVersionFormat(object arg0, object arg1) {
            return string.Format(_resourceCulture, FileHasVersion, arg0, arg1);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Incorrect argument count {0}; expected to be {1} or {2}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <param name="arg1">An object (1) to format.</param>
        /// <param name="arg2">An object (2) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string IncorrectArgumentCountFormat(object arg0, object arg1, object arg2) {
            return string.Format(_resourceCulture, IncorrectArgumentCount, arg0, arg1, arg2);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Incorrect command {0}; expected to be {1} or {2}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <param name="arg1">An object (1) to format.</param>
        /// <param name="arg2">An object (2) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string IncorrectCommandFormat(object arg0, object arg1, object arg2) {
            return string.Format(_resourceCulture, IncorrectCommand, arg0, arg1, arg2);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Syntax error on token {0}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string SyntaxErrorDescriptionFormat(object arg0) {
            return string.Format(_resourceCulture, SyntaxErrorDescription, arg0);
        }
    }
}
